In [1]:
#Importing modules
import os
import mne
import numpy as np
import pandas as df
from scipy.signal import butter, lfilter
from scipy.signal import freqz

In [2]:
#dropping the eog channels as we will be working only on 22 eeg channels
file_paths_1 = [
    'B0101T.gdf',
    
    'B0103T.gdf',
    'B0201T.gdf',
    'B0202T.gdf',
    'B0203T.gdf',
    'B0301T.gdf',
    'B0302T.gdf',
    'B0303T.gdf',
    'B0401T.gdf',
    'B0402T.gdf',
    'B0403T.gdf',
    'B0501T.gdf',
    'B0502T.gdf',
    'B0503T.gdf',
    'B0601T.gdf',
    'B0602T.gdf',
    'B0603T.gdf',
    'B0701T.gdf',
    'B0702T.gdf',
    'B0703T.gdf',
    'B0801T.gdf',
    'B0802T.gdf',
    'B0803T.gdf',
    'B0901T.gdf',
    'B0902T.gdf',
    'B0903T.gdf'
]

raw = []

for file_path in file_paths_1:
    raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])
    
    p=raw_data.drop_channels(['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])
    raw.append(p)
    
#This file has no EOG channel
#raw_data1 =mne.io.read_raw_gdf("B0102T.gdf")
#raw.append(raw_data1)

Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0101T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12704\2529578853.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0103T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 469010  =      0.000 ...  1876.040 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12704\2529578853.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0201T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12704\2529578853.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0202T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12704\2529578853.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0203T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 464154  =      0.000 ...  1856.616 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12704\2529578853.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0301T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12704\2529578853.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0302T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12704\2529578853.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0303T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 464674  =      0.000 ...  1858.696 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12704\2529578853.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0401T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12704\2529578853.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0402T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 696265  =      0.000 ...  2785.060 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12704\2529578853.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0403T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 468558  =      0.000 ...  1874.232 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12704\2529578853.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0501T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12704\2529578853.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0502T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 696265  =      0.000 ...  2785.060 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12704\2529578853.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0503T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 461874  =      0.000 ...  1847.496 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12704\2529578853.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0601T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12704\2529578853.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0602T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12704\2529578853.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0603T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 470390  =      0.000 ...  1881.560 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12704\2529578853.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0701T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12704\2529578853.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0702T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12704\2529578853.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0703T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 466726  =      0.000 ...  1866.904 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12704\2529578853.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0801T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 787728  =      0.000 ...  3150.912 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12704\2529578853.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0802T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12704\2529578853.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0803T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 474834  =      0.000 ...  1899.336 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12704\2529578853.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0901T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12704\2529578853.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0902T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12704\2529578853.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0903T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 460730  =      0.000 ...  1842.920 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12704\2529578853.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


In [3]:
raw[25].info

<Info | 7 non-empty values
 bads: []
 ch_names: EEG:C3, EEG:Cz, EEG:C4
 chs: 3 EEG
 custom_ref_applied: False
 highpass: 0.0 Hz
 lowpass: 125.0 Hz
 meas_date: 2005-12-09 09:20:50 UTC
 nchan: 3
 projs: []
 sfreq: 250.0 Hz
>

In [4]:
#Annotation object for annotating segments of raw data.
for i in range(0,26):
    raw[i].annotations
    events=mne.events_from_annotations(raw[i])
    #printing the 1st index of the events which contains the overall details of the file
    events[1]
    

Used Annotations descriptions: ['1023', '1077', '1078', '1079', '1081', '276', '277', '32766', '768', '769', '770']
Used Annotations descriptions: ['1023', '1077', '1078', '1079', '1081', '276', '277', '32766', '768', '769', '770', '781']
Used Annotations descriptions: ['1023', '1077', '1078', '1079', '1081', '276', '277', '32766', '768', '769', '770']
Used Annotations descriptions: ['1023', '1077', '1078', '1079', '1081', '276', '277', '32766', '768', '769', '770']
Used Annotations descriptions: ['1023', '1077', '1078', '1079', '1081', '276', '277', '32766', '768', '769', '770', '781']
Used Annotations descriptions: ['1023', '1077', '1078', '1079', '1081', '276', '277', '32766', '768', '769', '770']
Used Annotations descriptions: ['1023', '1077', '1078', '1079', '1081', '276', '277', '32766', '768', '769', '770']
Used Annotations descriptions: ['1023', '1077', '1078', '1079', '1081', '276', '277', '32766', '768', '769', '770', '781']
Used Annotations descriptions: ['1023', '1077', '10

In [5]:
#events[0] contains the main data in which we should work on 
events[0][0:20]

array([[    0,     0,     8],
       [  499,     0,     6],
       [16749,     0,     7],
       [32999,     0,     5],
       [37999,     0,     4],
       [42999,     0,     3],
       [47999,     0,     2],
       [52251,     0,     8],
       [54349,     0,     9],
       [55099,     0,    11],
       [55224,     0,    12],
       [56938,     0,     9],
       [56938,     0,     1],
       [57688,     0,    10],
       [57813,     0,    12],
       [59516,     0,     9],
       [60266,     0,    10],
       [60391,     0,    12],
       [61822,     0,     9],
       [62572,     0,    11]])

In [6]:
#creating a event dictionary
event_dict={
 'rejected trial':1,
 'horizontal eye movement':2,
 'vertical eye movement':3,
 'eye rotation':4,
 'eye blinks':5,
 'eye open':6,
 'eye close':7,
 'start of a new run':8,
 'start of a trial':9,
 'class 1':10,
 'class 2':11,
 'BCI feedback':12,
 }

In [7]:
for i in range(0,26):
    rawinfo=raw[i].info

In [8]:
rawinfo

<Info | 7 non-empty values
 bads: []
 ch_names: EEG:C3, EEG:Cz, EEG:C4
 chs: 3 EEG
 custom_ref_applied: False
 highpass: 0.0 Hz
 lowpass: 125.0 Hz
 meas_date: 2005-12-09 09:20:50 UTC
 nchan: 3
 projs: []
 sfreq: 250.0 Hz
>

In [9]:
# Create an epoch with tmin=0.0 and set baseline explicitly
epochs = mne.Epochs(raw[0], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
# Now you can select the data between 3.0 and 7.5 seconds
classA = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data() # 'data_within_range' now contains the EEG data from 3.0 to 7.5 seconds without baseline correction.
epochs = mne.Epochs(raw[1], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classA1 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classA= np.append(classA,classA1)
epochs = mne.Epochs(raw[2], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classA2 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classA= np.append(classA,classA2)
epochs = mne.Epochs(raw[3], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classA3 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classA= np.append(classA,classA3)
epochs = mne.Epochs(raw[4], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classA4 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classA= np.append(classA,classA4)
epochs = mne.Epochs(raw[5], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classA5 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classA= np.append(classA,classA5)
epochs = mne.Epochs(raw[6], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classA6 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classA= np.append(classA,classA6)
epochs = mne.Epochs(raw[7], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classA7 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classA= np.append(classA,classA7)
epochs = mne.Epochs(raw[8], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classA8 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classA= np.append(classA,classA8)
epochs = mne.Epochs(raw[9], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classA9 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classA= np.append(classA,classA9)
epochs = mne.Epochs(raw[10], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classA10 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classA= np.append(classA,classA10)
epochs = mne.Epochs(raw[11], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classA11 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classA= np.append(classA,classA11)
epochs = mne.Epochs(raw[12], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classA12 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classA= np.append(classA,classA12)
epochs = mne.Epochs(raw[13], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classA13 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classA= np.append(classA,classA13)
epochs = mne.Epochs(raw[14], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classA14 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classA= np.append(classA,classA14)
epochs = mne.Epochs(raw[15], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classA15 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classA= np.append(classA,classA15)
epochs = mne.Epochs(raw[16], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classA16 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classA= np.append(classA,classA16)
epochs = mne.Epochs(raw[17], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classA17 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classA= np.append(classA,classA17)
epochs = mne.Epochs(raw[18], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classA18 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classA= np.append(classA,classA18)
epochs = mne.Epochs(raw[19], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classA19 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classA= np.append(classA,classA19)
epochs = mne.Epochs(raw[20], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classA20 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classA= np.append(classA,classA20)
epochs = mne.Epochs(raw[21], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classA21 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classA= np.append(classA,classA21)
epochs = mne.Epochs(raw[22], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classA22 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classA= np.append(classA,classA22)
epochs = mne.Epochs(raw[23], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classA23 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classA= np.append(classA,classA23)
epochs = mne.Epochs(raw[24], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classA24 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classA= np.append(classA,classA24)
epochs = mne.Epochs(raw[25], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classA25 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classA= np.append(classA,classA25)

'''epochs = mne.Epochs(raw[26], events[0], new_event_id=[4], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classA26 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classA= np.append(classA,classA26)'''


Not setting metadata
80 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 80 events and 1876 original time points ...
0 bad epochs dropped
Not setting metadata
80 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 80 events and 1876 original time points ...
0 bad epochs dropped
Not setting metadata
80 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 80 events and 1876 original time points ...
0 bad epochs dropped
Not setting metadata
80 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 80 events and 1876 original time points ...
0 bad epochs dropped
Not setting metadata
80 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from pre

'epochs = mne.Epochs(raw[26], events[0], new_event_id=[4], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)\nclassA26 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()\nclassA= np.append(classA,classA26)'

In [10]:
epochs = mne.Epochs(raw[0], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classB = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
epochs = mne.Epochs(raw[1], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classB1 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classB= np.append(classB,classB1)
epochs = mne.Epochs(raw[2], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classB2 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classB= np.append(classB,classB2)
epochs = mne.Epochs(raw[3], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classB3 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classB= np.append(classB,classB3)
epochs = mne.Epochs(raw[4], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classB4 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classB= np.append(classB,classB4)
epochs = mne.Epochs(raw[5], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classB5 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classB= np.append(classB,classB5)
epochs = mne.Epochs(raw[6], events[0], event_id=[1], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classB6 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classB= np.append(classB,classB6)
epochs = mne.Epochs(raw[7], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classB7 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classB= np.append(classB,classB7)
epochs = mne.Epochs(raw[8], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classB8 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classB= np.append(classB,classB8)
epochs = mne.Epochs(raw[9], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classB9 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classB= np.append(classB,classB9)
epochs = mne.Epochs(raw[10], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classB10 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classB= np.append(classB,classB10)
epochs = mne.Epochs(raw[11], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classB11 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classB= np.append(classB,classB11)
epochs = mne.Epochs(raw[12], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classB12 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classB= np.append(classB,classB12)
epochs = mne.Epochs(raw[13], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classB13 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classB= np.append(classB,classB13)
epochs = mne.Epochs(raw[14], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classB14 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classB= np.append(classB,classB14)
epochs = mne.Epochs(raw[15], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classB15 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classB= np.append(classB,classB15)
epochs = mne.Epochs(raw[16], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classB16 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classB= np.append(classB,classB16)
epochs = mne.Epochs(raw[17], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classB17 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classB= np.append(classB,classB17)
epochs = mne.Epochs(raw[18], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classB18 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classB= np.append(classB,classB18)
epochs = mne.Epochs(raw[19], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classB19 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classB= np.append(classB,classB19)
epochs = mne.Epochs(raw[20], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classB20 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classB= np.append(classB,classB20)
epochs = mne.Epochs(raw[21], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classB21 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classB= np.append(classB,classB21)
epochs = mne.Epochs(raw[22], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classB22 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classB= np.append(classB,classB22)
epochs = mne.Epochs(raw[23], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classB23 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classB= np.append(classB,classB23)
epochs = mne.Epochs(raw[24], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classB24 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classB= np.append(classB,classB24)
epochs = mne.Epochs(raw[25], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
classB25 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
classB= np.append(classB,classB25)
#epochs = mne.Epochs(raw[26], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
#classA26 = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data()
#classA= np.append(classA,classA26)



Not setting metadata
80 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 80 events and 1876 original time points ...
0 bad epochs dropped
Not setting metadata
80 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 80 events and 1876 original time points ...
0 bad epochs dropped
Not setting metadata
80 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 80 events and 1876 original time points ...
0 bad epochs dropped
Not setting metadata
80 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 80 events and 1876 original time points ...
0 bad epochs dropped
Not setting metadata
80 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from pre

In [11]:
classA.shape

(7026240,)

In [12]:
classB.shape

(6840450,)

In [13]:
#printing the shape of the first class(left hand)
newA=classA.reshape(2080,3,1126)
newA.shape
#type(newA)

(2080, 3, 1126)

In [14]:
newB=classB.reshape(2025,3,1126)
#newA.shape
newB.shape

(2025, 3, 1126)

In [15]:
import scipy.signal as signal

# Define the notch filter parameters
fs = 250  # Sampling frequency
notch_freq = 50.0  # Powerline frequency in Hz
Q = 30.0  # Quality factor

# Design a notch filter
b, a = signal.iirnotch(notch_freq, Q, fs)

# Apply the notch filter to EEG segments
def apply_notch_filter(eeg_segments):
    num_segments, num_channels, segment_length = eeg_segments.shape
    filtered_segments = np.zeros_like(eeg_segments)

    for i in range(num_segments):
        for j in range(num_channels):
            filtered_segments[i, j] = signal.lfilter(b, a, eeg_segments[i, j])
            
    return filtered_segments

filtered_class_A_segments = apply_notch_filter(newA)
filtered_class_B_segments = apply_notch_filter(newB)

# Now the EEG segments for both classes have the 50Hz powerline frequency removed


In [16]:
filtered_class_A_segments.shape

(2080, 3, 1126)

In [17]:
#printing the classA (first class details)
A=[0]
#A=mne.EpochsArray(filtered_class_A_segments,rawinfo)
A=mne.EpochsArray(newA,rawinfo)
A

Not setting metadata
2080 matching events found
No baseline correction applied
0 projection items activated


<EpochsArray |  2080 events (all good), 0 - 4.5 sec, baseline off, ~53.6 MB, data loaded,
 '1': 2080>

In [18]:
B=[0]
#B=mne.EpochsArray(filtered_class_B_segments,rawinfo)
B=mne.EpochsArray(newB,rawinfo)
B

Not setting metadata
2025 matching events found
No baseline correction applied
0 projection items activated


<EpochsArray |  2025 events (all good), 0 - 4.5 sec, baseline off, ~52.2 MB, data loaded,
 '1': 2025>

In [19]:
#building the bandpass filter function
def butter_bandpass_filter(signal, lowcut, highcut, fs, order=5):
    nyq = 0.5 * fs
    low = lowcut/nyq
    high = highcut/nyq
    b,a = butter(order, [low, high], btype='band')
    y = lfilter(b, a, signal, axis=-1)  
    return y

In [20]:
#delta bandpass filter from class A
def read_da(path):
    fs = 250
    lowcut = 0.5
    highcut = 3.99
    delta= butter_bandpass_filter(A, lowcut, highcut, fs, order=5)
    mean_filtered_data = np.mean(delta, axis=-1)
    return mean_filtered_data

In [21]:
#getting the shape of the delta for classA
deltaA=[0]
deltaA=read_da(A)
print(deltaA.shape)

(2080, 3)


In [22]:
#delta bandpass filter from class B
def read_db(path):
    fs = 250
    lowcut = 0.5
    highcut = 3.99
    delta= butter_bandpass_filter(B, lowcut, highcut, fs, order=5)
    delta = np.mean(delta, axis=-1)
    return delta

In [23]:
#getting the shape of the delta for classB
deltaB=[0] 
deltaB=read_db(B)
print(deltaB.shape)

(2025, 3)


In [24]:
#theta bandpass filter from class A
def read_de(path):
    fs = 250
    lowcut = 4
    highcut = 7.99
    theta= butter_bandpass_filter(A, lowcut, highcut, fs, order=5)
    theta = np.mean(theta, axis=-1)
    return theta

In [25]:
#getting the shape of the theta for class A
thetaA=[0]
thetaA=read_de(A)
print(thetaA.shape)

(2080, 3)


In [26]:
#Theta bandpass filter from class B
def read_df(path):
    fs = 250
    lowcut = 4
    highcut = 7.99
    theta= butter_bandpass_filter(B, lowcut, highcut, fs, order=5)
    theta = np.mean(theta, axis=-1)
    return theta

In [27]:
#getting the shape of the theta for class B
thetaB=[0]
thetaB=read_df(B)
print(thetaB.shape)

(2025, 3)


In [28]:
#Alpha bandpass filter from class A
def read_di(path):
    fs = 250
    lowcut = 8.01
    highcut = 11.99
    alpha= butter_bandpass_filter(A, lowcut, highcut, fs, order=5)
    alpha = np.mean(alpha, axis=-1)
    return alpha

In [29]:
#getting the shape of the alpha for class A
alphaA=[0]
alphaA=read_di(A)
print(alphaA.shape)

(2080, 3)


In [30]:
#Alpha bandpass filter from class B
def read_dj(path):
    fs = 250
    lowcut = 8.01
    highcut = 11.99
    alpha= butter_bandpass_filter(B, lowcut, highcut, fs, order=5)
    alpha = np.mean(alpha, axis=-1)
    return alpha

In [31]:
#getting the shape of the alpha of class B
alphaB=[0]
alphaB=read_dj(B)
print(alphaB.shape)

(2025, 3)


In [32]:
#Beta bandpass filter from class A
def read_dm(path):
    fs = 250
    lowcut = 12.01
    highcut = 29.99
    beta= butter_bandpass_filter(A, lowcut, highcut, fs, order=5)
    beta = np.mean(beta, axis=-1)
    return beta

In [33]:
#getting the shape of the beta of class A
betaA=[0]
betaA=read_dm(A)
print(betaA.shape)

(2080, 3)


In [34]:
#Beta bandpass filter from class B
def read_dn(path):
    fs = 250
    lowcut = 12.01
    highcut = 29.99
    beta= butter_bandpass_filter(B, lowcut, highcut, fs, order=5)
    beta = np.mean(beta, axis=-1)
    return beta

In [35]:
#getting the shape of the beta of class B
betaB=[0]
betaB=read_dn(B)
print(betaB.shape)

(2025, 3)


In [36]:
#Gamma bandpass filter from class A
def read_dq(path):
    fs = 250
    lowcut = 30.01
    highcut = 100
    gamma= butter_bandpass_filter(A, lowcut, highcut, fs, order=5)
    gamma = np.mean(gamma, axis=-1)
    return gamma

In [37]:
#getting the shape of the gamma of class A
gammaA=[0]
gammaA=read_dq(A)
print(gammaA.shape)

(2080, 3)


In [38]:
#Gamma bandpass filter from class B
def read_dr(path):
    fs = 250
    lowcut = 30.01
    highcut = 100
    gamma= butter_bandpass_filter(B, lowcut, highcut, fs, order=5)
    gamma = np.mean(gamma, axis=-1)
    return gamma

In [39]:
#getting the shape of the gamma of class B
gammaB=[0]
gammaB=read_dr(B)
print(gammaB.shape)

(2025, 3)


In [40]:
def calculate_mean_median_features(eeg_signals):
    mean_median_features = []

    for signal in eeg_signals:
        segment_features = []

        for segment in signal:
            mean_feat = np.mean(segment)
            median_feat = np.median(segment)
            
            segment_features.append(mean_feat)
            segment_features.append(median_feat)
        
        mean_median_features.append(segment_features)

    return np.array(mean_median_features)

In [41]:
meanmedianA=calculate_mean_median_features(A)
meanmedianA.shape

(2080, 6)

In [42]:
meanmedianB=calculate_mean_median_features(B)
meanmedianB.shape

(2025, 6)

In [43]:
# Calculate Hjorth parameters for each EEG segment
def hjorth_parameters(eeg_segment):
    activity = np.var(eeg_segment)
    diff_signal = np.diff(eeg_segment)
    mobility = np.var(diff_signal)
    diff2_signal = np.diff(diff_signal)
    complexity = np.var(diff2_signal)
    
    return activity, mobility, complexity

# Calculate Hjorth features for all segments in the EEG signals
def calculate_hjorth_features(eeg_signals):
    hjorth_features = []

    for signal in eeg_signals:
        segment_features = []

        for segment in signal:
            hjorth_feats = hjorth_parameters(segment)
            segment_features.extend(hjorth_feats)
        
        hjorth_features.append(segment_features)

    return np.array(hjorth_features)

In [44]:
hjorth_features_class_A = calculate_hjorth_features(A)
hjorth_features_class_B = calculate_hjorth_features(B)

# Create labels for class A and class B
labels_class_A = np.zeros(len(hjorth_features_class_A))  
labels_class_B = np.ones(len(hjorth_features_class_B))   

# Concatenate the Hjorth features and labels for both classes
all_hjorth_features = np.concatenate((hjorth_features_class_A, hjorth_features_class_B), axis=0)
all_labels = np.concatenate((labels_class_A, labels_class_B))
#all_labels[0]

In [45]:
def shannon_entropy(signal):
    # Compute the histogram of the signal
    hist, _ = np.histogram(signal, bins=256, range=(0, 256))
    
    # Normalize the histogram
    hist = hist / (len(signal) * 1.0)
    
    # Calculate Shannon entropy
    entropy = -np.sum([p * np.log2(p + np.finfo(float).eps) for p in hist if p > 0])
    
    return entropy

def calculate_shannon_entropy_features(eeg_signals):
    shannon_entropy_features = []

    for signal in eeg_signals:
        segment_features = []

        for segment in signal:
            entropy_feat = shannon_entropy(segment)
            segment_features.append(entropy_feat)
        
        shannon_entropy_features.append(segment_features)

    return np.array(shannon_entropy_features)

In [46]:
#!pip install PyWavelets

In [47]:
shanon_A=calculate_shannon_entropy_features(A)
shanon_A.shape

(2080, 3)

In [48]:
shanon_B=calculate_shannon_entropy_features(B)
shanon_B.shape

(2025, 3)

In [49]:
import pywt

def calculate_wavelet_features(eeg_signals, wavelet='db4', level=4):
    wavelet_features = []

    for signal in eeg_signals:
        segment_features = []

        for segment in signal:
            # Apply discrete wavelet transform
            coeffs = pywt.wavedec(segment, wavelet, level=level)
            
            # Extract the approximation and detail coefficients
            approx = coeffs[0]
            details = np.concatenate(coeffs[1:])
            
            # Calculate statistical features (mean, variance, etc.) on coefficients
            mean = np.mean(details)
            variance = np.var(details)
            energy = np.sum(np.square(details))
            
            # Append wavelet features for this segment
            segment_features.extend([mean, variance, energy])
        
        wavelet_features.append(segment_features)

    return np.array(wavelet_features)

In [50]:
# Example usage:
# Assuming eeg_signals is a list of EEG signal segments, where each segment is a 1D numpy array.
wavelet_features_A = calculate_wavelet_features(A)
wavelet_features_A.shape

(2080, 9)

In [51]:
wavelet_features_B = calculate_wavelet_features(B)
wavelet_features_B.shape

(2025, 9)

In [52]:
#!pip install scipy

In [53]:
from scipy.stats import skew, kurtosis

def calculate_skewness_kurtosis_features(eeg_signals):
    skewness_features = []
    kurtosis_features = []

    for signal in eeg_signals:
        segment_skewness = []
        segment_kurtosis = []

        for segment in signal:
            # Calculate skewness and kurtosis for each segment
            skew_val = skew(segment)
            kurtosis_val = kurtosis(segment)

            segment_skewness.append(skew_val)
            segment_kurtosis.append(kurtosis_val)

        # Append skewness and kurtosis features for this signal
        skewness_features.append(segment_skewness)
        kurtosis_features.append(segment_kurtosis)

    return np.array(skewness_features), np.array(kurtosis_features)

# Example usage:
# Assuming eeg_signals is a list of EEG signal segments, where each segment is a 1D numpy array.


In [54]:
skewness_A, kurtosis_A = calculate_skewness_kurtosis_features(A)
skewness_A.shape

(2080, 3)

In [55]:
kurtosis_A.shape

(2080, 3)

In [56]:
skewness_B, kurtosis_B = calculate_skewness_kurtosis_features(B)
skewness_B.shape

(2025, 3)

In [57]:
kurtosis_B.shape

(2025, 3)

In [58]:
aDelta=np.append(deltaA,deltaB)
aDelta.shape

(12315,)

In [59]:
deltaAll=aDelta.reshape(4105,3)
deltaAll.shape

(4105, 3)

In [60]:
aTheta=np.append(thetaA,thetaB)
aTheta.shape

(12315,)

In [61]:
thetaAll=aTheta.reshape(4105,3)
thetaAll.shape

(4105, 3)

In [62]:
aAlpha=np.append(alphaA,alphaB)
aAlpha.shape

(12315,)

In [63]:
alphaAll=aAlpha.reshape(4105,3)
alphaAll.shape

(4105, 3)

In [64]:
aBeta=np.append(betaA,betaB)
aBeta.shape

(12315,)

In [65]:
betaAll=aBeta.reshape(4105,3)
betaAll.shape

(4105, 3)

In [66]:
aGamma=np.append(gammaA,gammaB)
aGamma.shape

(12315,)

In [67]:
gammaAll=aGamma.reshape(4105,3)
gammaAll.shape

(4105, 3)

In [68]:
hjorthAll=np.append(hjorth_features_class_A,hjorth_features_class_B)
hjorthAll.shape

(36945,)

In [69]:
hjorthAll=hjorthAll.reshape(4105,9)
hjorthAll.shape

(4105, 9)

In [70]:
meanmedianAll=np.append(meanmedianA,meanmedianB)
meanmedianAll.shape

(24630,)

In [71]:
meanmedianAll=meanmedianAll.reshape(4105,6)
meanmedianAll.shape

(4105, 6)

In [72]:
shanonAll=np.append(shanon_A,shanon_B)
shanonAll.shape

(12315,)

In [73]:
shanonAll=shanonAll.reshape(4105,3)
shanonAll.shape

(4105, 3)

In [74]:
wavelet_featuresAll=np.append(wavelet_features_A,wavelet_features_B)
wavelet_featuresAll.shape

(36945,)

In [75]:
wavelet_featuresAll=wavelet_featuresAll.reshape(4105,9)
wavelet_featuresAll.shape

(4105, 9)

In [76]:
skewnessAll=np.append(skewness_A,skewness_B)
skewnessAll.shape

(12315,)

In [77]:
skewnessAll=skewnessAll.reshape(4105,3)
skewnessAll.shape

(4105, 3)

In [78]:
kurtosisAll=np.append(kurtosis_A,kurtosis_B)
kurtosisAll.shape

(12315,)

In [79]:
kurtosisAll=kurtosisAll.reshape(4105,3)
kurtosisAll.shape

(4105, 3)

In [80]:
otherData=np.column_stack((deltaAll,thetaAll,alphaAll,betaAll,gammaAll,hjorthAll,meanmedianAll,shanonAll,wavelet_featuresAll,skewnessAll, kurtosisAll))
otherData.shape

(4105, 48)

In [81]:
xpother=np.empty(4105,dtype=int)

In [82]:
for i in range(0,2080):
    xpother[i]=0
for i in range(2080,4105):
    xpother[i]=1
xpother.shape

(4105,)

In [83]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(otherData,xpother,test_size=0.2,random_state=0)

In [84]:
from sklearn.preprocessing import StandardScaler
ac=StandardScaler()
x_train=ac.fit_transform(x_train)
x_test=ac.transform(x_test)

In [85]:
from sklearn.neighbors import KNeighborsClassifier 
classknn=KNeighborsClassifier(n_neighbors=10,metric='minkowski',p=2)
classknn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=10)

In [86]:
y_pred=classknn.predict(x_test)
y_pred.shape
#y_pred=classifier.predict(y_test_n)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))


[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 0]
 [0 0]]


In [87]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test,y_pred))


[[249 161]
 [253 158]]
0.49573690621193667


In [88]:
from scipy.stats import pearsonr
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier 
mic_scores = []
selected_features=[]
def calculate_MIC(x, y):
    # Calculate Pearson correlation coefficient (r) between x and y
    r, _ = pearsonr(x, y)
    
    # Calculate MIC using the formula MIC = |r| * log2(n)
    n = len(x)
    mic = abs(r) * np.log2(n)
    
    return mic

for i in range(0,48):
    #mine.compute_score(x_train[:, feature_idx], y_train)
    mic_score = calculate_MIC(otherData[:, i], xpother)
    mic_scores.append(mic_score)


# Sort features based on MIC scores (in descending order)
sorted_features = np.argsort(mic_scores)[::-1]

# Select the top 20 features
for i in range(2,48):
    top_20_features = sorted_features[:i]
    top_20_feature_values = otherData[:, top_20_features]
    
    x_train,x_test,y_train,y_test=train_test_split(top_20_feature_values,xpother,test_size=0.2,random_state=0)
   
    ac=StandardScaler()
    x_train=ac.fit_transform(x_train)
    x_test=ac.transform(x_test)
    
    classknn=KNeighborsClassifier(n_neighbors=9,metric='minkowski',p=2)
    classknn.fit(x_train,y_train)
    y_pred=classknn.predict(x_test)
    cm= confusion_matrix(y_test, y_pred)
    print("No of Feature selected :",i)
    print(cm)
    print(accuracy_score(y_test,y_pred))


No of Feature selected : 2
[[210 200]
 [216 195]]
0.4933008526187576
No of Feature selected : 3
[[213 197]
 [208 203]]
0.5066991473812423
No of Feature selected : 4
[[235 175]
 [189 222]]
0.5566382460414129
No of Feature selected : 5
[[224 186]
 [210 201]]
0.5176613885505481
No of Feature selected : 6
[[223 187]
 [217 194]]
0.5079171741778319
No of Feature selected : 7
[[223 187]
 [217 194]]
0.5079171741778319
No of Feature selected : 8
[[213 197]
 [199 212]]
0.5176613885505481
No of Feature selected : 9
[[218 192]
 [200 211]]
0.5225334957369062
No of Feature selected : 10
[[211 199]
 [195 216]]
0.5200974421437271
No of Feature selected : 11
[[215 195]
 [198 213]]
0.5213154689403167
No of Feature selected : 12
[[208 202]
 [208 203]]
0.5006090133982948
No of Feature selected : 13
[[203 207]
 [196 215]]
0.5091352009744214
No of Feature selected : 14
[[207 203]
 [201 210]]
0.5079171741778319
No of Feature selected : 15
[[208 202]
 [193 218]]
0.5188794153471377
No of Feature selected : 16


In [89]:
#Highest accuracy gained after feature selection using knn
top_20_features = sorted_features[:4]
top_20_feature_values = otherData[:, top_20_features]
#train-test
x_train,x_test,y_train,y_test=train_test_split(top_20_feature_values,xpother,test_size=0.2,random_state=0)
#feature-scaling
ac=StandardScaler()
x_train=ac.fit_transform(x_train)
x_test=ac.transform(x_test)
#classification
classknn=KNeighborsClassifier(n_neighbors=9,metric='minkowski',p=2)
classknn.fit(x_train,y_train)
#prediction
y_pred=classknn.predict(x_test)
#confusion matrix
cm= confusion_matrix(y_test, y_pred)
print("No of Feature selected :4")
print(cm)
print(accuracy_score(y_test,y_pred))

No of Feature selected :4
[[235 175]
 [189 222]]
0.5566382460414129
