In [1]:
#Importing modules
import os
import mne
import numpy as np
import pandas as df
from scipy.signal import butter, lfilter
from scipy.signal import freqz

In [2]:
#dropping the eog channels as we will be working only on 22 eeg channels
file_paths_1 = [
    'B0101T.gdf',
    
    'B0103T.gdf',
    'B0201T.gdf',
    'B0202T.gdf',
    'B0203T.gdf',
    'B0301T.gdf',
    'B0302T.gdf',
    'B0303T.gdf',
    'B0401T.gdf',
    'B0402T.gdf',
    'B0403T.gdf',
    'B0501T.gdf',
    'B0502T.gdf',
    'B0503T.gdf',
    'B0601T.gdf',
    'B0602T.gdf',
    'B0603T.gdf',
    'B0701T.gdf',
    'B0702T.gdf',
    'B0703T.gdf',
    'B0801T.gdf',
    'B0802T.gdf',
    'B0803T.gdf',
    'B0901T.gdf',
    'B0902T.gdf',
    'B0903T.gdf'
]

raw = []

for file_path in file_paths_1:
    raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])
    
    p=raw_data.drop_channels(['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])
    raw.append(p)
    
#This file has no EOG channel
raw_data1 =mne.io.read_raw_gdf("B0102T.gdf")
raw.append(raw_data1)

Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0101T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0103T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 469010  =      0.000 ...  1876.040 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0201T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0202T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0203T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 464154  =      0.000 ...  1856.616 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0301T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0302T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0303T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 464674  =      0.000 ...  1858.696 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0401T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0402T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 696265  =      0.000 ...  2785.060 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0403T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 468558  =      0.000 ...  1874.232 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0501T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0502T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 696265  =      0.000 ...  2785.060 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0503T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 461874  =      0.000 ...  1847.496 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0601T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0602T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0603T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 470390  =      0.000 ...  1881.560 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0701T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0702T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0703T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 466726  =      0.000 ...  1866.904 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0801T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 787728  =      0.000 ...  3150.912 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0802T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0803T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 474834  =      0.000 ...  1899.336 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0901T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0902T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 604802  =      0.000 ...  2419.208 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0903T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4
Creating raw.info structure...
Reading 0 ... 460730  =      0.000 ...  1842.920 secs...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:35: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG:ch01', 'EOG:ch02', 'EOG:ch03'])


Extracting EDF parameters from C:\Users\Lenovo\Desktop\JU\2b_dataset\B0102T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG:C3, EEG:Cz, EEG:C4, EOG:ch01, EOG:ch02, EOG:ch03
Creating raw.info structure...


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21188\2075795585.py:41: RuntimeWarning: Highpass cutoff frequency 100.0 is greater than lowpass cutoff frequency 0.5, setting values to 0 and Nyquist.
  raw_data1 =mne.io.read_raw_gdf("B0102T.gdf")


In [3]:
for i in range(0,26):
    print(raw[i].info)

<Info | 7 non-empty values
 bads: []
 ch_names: EEG:C3, EEG:Cz, EEG:C4
 chs: 3 EEG
 custom_ref_applied: False
 highpass: 0.0 Hz
 lowpass: 125.0 Hz
 meas_date: 2005-10-25 09:35:11 UTC
 nchan: 3
 projs: []
 sfreq: 250.0 Hz
>
<Info | 7 non-empty values
 bads: []
 ch_names: EEG:C3, EEG:Cz, EEG:C4
 chs: 3 EEG
 custom_ref_applied: False
 highpass: 0.0 Hz
 lowpass: 125.0 Hz
 meas_date: 2005-11-30 10:44:29 UTC
 nchan: 3
 projs: []
 sfreq: 250.0 Hz
>
<Info | 7 non-empty values
 bads: []
 ch_names: EEG:C3, EEG:Cz, EEG:C4
 chs: 3 EEG
 custom_ref_applied: False
 highpass: 0.0 Hz
 lowpass: 125.0 Hz
 meas_date: 2005-10-25 11:59:13 UTC
 nchan: 3
 projs: []
 sfreq: 250.0 Hz
>
<Info | 7 non-empty values
 bads: []
 ch_names: EEG:C3, EEG:Cz, EEG:C4
 chs: 3 EEG
 custom_ref_applied: False
 highpass: 0.0 Hz
 lowpass: 125.0 Hz
 meas_date: 2005-10-31 10:47:27 UTC
 nchan: 3
 projs: []
 sfreq: 250.0 Hz
>
<Info | 7 non-empty values
 bads: []
 ch_names: EEG:C3, EEG:Cz, EEG:C4
 chs: 3 EEG
 custom_ref_applied: Fals

In [4]:
#Annotation object for annotating segments of raw data.
for i in range(0,26):
    raw[i].annotations
    events=mne.events_from_annotations(raw[i])
    #printing the 1st index of the events which contains the overall details of the file
    events[1]
    

Used Annotations descriptions: ['1023', '1077', '1078', '1079', '1081', '276', '277', '32766', '768', '769', '770']
Used Annotations descriptions: ['1023', '1077', '1078', '1079', '1081', '276', '277', '32766', '768', '769', '770', '781']
Used Annotations descriptions: ['1023', '1077', '1078', '1079', '1081', '276', '277', '32766', '768', '769', '770']
Used Annotations descriptions: ['1023', '1077', '1078', '1079', '1081', '276', '277', '32766', '768', '769', '770']
Used Annotations descriptions: ['1023', '1077', '1078', '1079', '1081', '276', '277', '32766', '768', '769', '770', '781']
Used Annotations descriptions: ['1023', '1077', '1078', '1079', '1081', '276', '277', '32766', '768', '769', '770']
Used Annotations descriptions: ['1023', '1077', '1078', '1079', '1081', '276', '277', '32766', '768', '769', '770']
Used Annotations descriptions: ['1023', '1077', '1078', '1079', '1081', '276', '277', '32766', '768', '769', '770', '781']
Used Annotations descriptions: ['1023', '1077', '10

In [5]:
#creating a event dictionary
event_dict={
 'rejected trial':1,
 'horizontal eye movement':2,
 'vertical eye movement':3,
 'eye rotation':4,
 'eye blinks':5,
 'eye open':6,
 'eye close':7,
 'start of a new run':8,
 'start of a trial':9,
 'class 1':10,
 'class 2':11,
 'BCI feedback':12,
 }

In [6]:
#Annotation object for annotating segments of raw data.
for i in range(0,26):
    raw[i].annotations
    events=mne.events_from_annotations(raw[i])
    #printing the 1st index of the events which contains the overall details of the file
    events[1]

Used Annotations descriptions: ['1023', '1077', '1078', '1079', '1081', '276', '277', '32766', '768', '769', '770']
Used Annotations descriptions: ['1023', '1077', '1078', '1079', '1081', '276', '277', '32766', '768', '769', '770', '781']
Used Annotations descriptions: ['1023', '1077', '1078', '1079', '1081', '276', '277', '32766', '768', '769', '770']
Used Annotations descriptions: ['1023', '1077', '1078', '1079', '1081', '276', '277', '32766', '768', '769', '770']
Used Annotations descriptions: ['1023', '1077', '1078', '1079', '1081', '276', '277', '32766', '768', '769', '770', '781']
Used Annotations descriptions: ['1023', '1077', '1078', '1079', '1081', '276', '277', '32766', '768', '769', '770']
Used Annotations descriptions: ['1023', '1077', '1078', '1079', '1081', '276', '277', '32766', '768', '769', '770']
Used Annotations descriptions: ['1023', '1077', '1078', '1079', '1081', '276', '277', '32766', '768', '769', '770', '781']
Used Annotations descriptions: ['1023', '1077', '10

In [7]:
#getting the rawinfo(information of each file)
rawinfo=[]
for i in range(0,26):
    rawinfo=np.append(rawinfo,raw[i].info)

In [8]:
#taking classA of 27 subjects
classA=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
for i in range(0,26):
    epochs = mne.Epochs(raw[i], events[0], event_id=[10], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
    classA[i] = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data() 

Not setting metadata
80 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 80 events and 1876 original time points ...
0 bad epochs dropped
Not setting metadata
80 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 80 events and 1876 original time points ...
0 bad epochs dropped
Not setting metadata
80 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 80 events and 1876 original time points ...
0 bad epochs dropped
Not setting metadata
80 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 80 events and 1876 original time points ...
0 bad epochs dropped
Not setting metadata
80 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from pre

In [9]:
#taking classA of 27 subjects
classB=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
for i in range(0,26):
    epochs = mne.Epochs(raw[i], events[0], event_id=[11], tmin=0.0, tmax=7.5, baseline=(0, 0), preload=True)
    classB[i] = epochs.copy().crop(tmin=3.0, tmax=7.5).get_data() 

Not setting metadata
80 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 80 events and 1876 original time points ...
0 bad epochs dropped
Not setting metadata
80 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 80 events and 1876 original time points ...
0 bad epochs dropped
Not setting metadata
80 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 80 events and 1876 original time points ...
0 bad epochs dropped
Not setting metadata
80 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 80 events and 1876 original time points ...
0 bad epochs dropped
Not setting metadata
80 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from pre

In [10]:
#converting the classA to epochsArray
A=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
for i in range(0,26):
    A[i]=mne.EpochsArray(classA[i],rawinfo[i])

Not setting metadata
80 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
80 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
80 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
80 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
80 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
80 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
80 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
80 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
80 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
80 matching events found


In [11]:
#converting the classA to epochsArray
B=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
for i in range(0,26):
    B[i]=mne.EpochsArray(classB[i],rawinfo[i])

Not setting metadata
80 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
80 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
80 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
80 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
80 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
80 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
80 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
80 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
80 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
80 matching events found


In [12]:
#feature scaling
for i in range(0,26):
    min_valA = np.min(A[i], axis=2, keepdims=True)
    max_valA = np.max(A[i], axis=2, keepdims=True)
    A[i] = (A[i] - min_valA) / (max_valA - min_valA)
    

In [13]:
#feature scaling
for i in range(0,8):
    min_valB = np.min(B[i], axis=2, keepdims=True)
    max_valB = np.max(B[i], axis=2, keepdims=True)
    B[i] = (B[i] - min_valB) / (max_valB - min_valB)

In [14]:
#Notch Filter if needed
'''import scipy.signal as signal

# Define the notch filter parameters
fs = 250  # Sampling frequency
notch_freq = 50.0  # Powerline frequency in Hz
Q = 30.0  # Quality factor

# Design a notch filter
b, a = signal.iirnotch(notch_freq, Q, fs)

# Apply the notch filter to EEG segments
def apply_notch_filter(eeg_segments):
    num_segments, num_channels, segment_length = eeg_segments.shape
    filtered_segments = np.zeros_like(eeg_segments)

    for i in range(num_segments):
        for j in range(num_channels):
            filtered_segments[i, j] = signal.lfilter(b, a, eeg_segments[i, j])
            
    return filtered_segments

filtered_class_A_segments = apply_notch_filter(newA)
filtered_class_B_segments = apply_notch_filter(newB)'''

# Now the EEG segments for both classes have the 50Hz powerline frequency removed


'import scipy.signal as signal\n\n# Define the notch filter parameters\nfs = 250  # Sampling frequency\nnotch_freq = 50.0  # Powerline frequency in Hz\nQ = 30.0  # Quality factor\n\n# Design a notch filter\nb, a = signal.iirnotch(notch_freq, Q, fs)\n\n# Apply the notch filter to EEG segments\ndef apply_notch_filter(eeg_segments):\n    num_segments, num_channels, segment_length = eeg_segments.shape\n    filtered_segments = np.zeros_like(eeg_segments)\n\n    for i in range(num_segments):\n        for j in range(num_channels):\n            filtered_segments[i, j] = signal.lfilter(b, a, eeg_segments[i, j])\n            \n    return filtered_segments\n\nfiltered_class_A_segments = apply_notch_filter(newA)\nfiltered_class_B_segments = apply_notch_filter(newB)'

In [15]:
#building the bandpass filter function
def butter_bandpass_filter(signal, lowcut, highcut, fs, order=5):
    nyq = 0.5 * fs
    low = lowcut/nyq
    high = highcut/nyq
    b,a = butter(order, [low, high], btype='band')
    y = lfilter(b, a, signal, axis=-1)  
    return y

In [16]:
#delta bandpass filter from class A
def read_da(i):
    fs = 250
    lowcut = 0.5
    highcut = 3.99
    delta= butter_bandpass_filter(A[i], lowcut, highcut, fs, order=5)
    mean_filtered_data = np.mean(delta, axis=-1)
    return mean_filtered_data

In [17]:
#calling the function for delta of classA separately for each files
deltaA=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
for i in range(0,26):
    deltaA[i]=read_da(i)


In [18]:
#delta bandpass filter from class B
def read_db(i):
    fs = 250
    lowcut = 0.5
    highcut = 3.99
    delta= butter_bandpass_filter(B[i], lowcut, highcut, fs, order=5)
    delta = np.mean(delta, axis=-1)
    return delta

In [19]:
#getting the shape of the delta for classB
deltaB=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
for i in range(0,26):
    deltaB[i]=read_db(i)

In [20]:
#theta bandpass filter from class A
def read_de(i):
    fs = 250
    lowcut = 4
    highcut = 7.99
    theta= butter_bandpass_filter(A[i], lowcut, highcut, fs, order=5)
    theta = np.mean(theta, axis=-1)
    return theta

In [21]:
#getting the shape of the theta for class A
thetaA=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
for i in range(0,26):
    thetaA[i]=read_de(i)

In [22]:
#Theta bandpass filter from class B
def read_df(i):
    fs = 250
    lowcut = 4
    highcut = 7.99
    theta= butter_bandpass_filter(B[i], lowcut, highcut, fs, order=5)
    theta = np.mean(theta, axis=-1)
    return theta

In [23]:
#getting the shape of the theta for class B
thetaB=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
for i in range(0,26):
    thetaB[i]=read_df(i)

In [24]:
#Alpha bandpass filter from class A
def read_di(i):
    fs = 250
    lowcut = 8.01
    highcut = 11.99
    alpha= butter_bandpass_filter(A[i], lowcut, highcut, fs, order=5)
    alpha = np.mean(alpha, axis=-1)
    return alpha

In [25]:
#getting the shape of the alpha for class A
alphaA=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
for i in range(0,26):
    alphaA[i]=read_di(i)

In [26]:
#Alpha bandpass filter from class B
def read_dj(i):
    fs = 250
    lowcut = 8.01
    highcut = 11.99
    alpha= butter_bandpass_filter(B[i], lowcut, highcut, fs, order=5)
    alpha = np.mean(alpha, axis=-1)
    return alpha

In [27]:
#getting the shape of the alpha of class B
alphaB=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
for i in range(0,26):
    alphaB[i]=read_dj(i)

In [28]:
#Beta bandpass filter from class A
def read_dm(i):
    fs = 250
    lowcut = 12.01
    highcut = 29.99
    beta= butter_bandpass_filter(A[i], lowcut, highcut, fs, order=5)
    beta = np.mean(beta, axis=-1)
    return beta

In [29]:
#getting the shape of the beta of class A
betaA=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
for i in range(0,26):
    betaA[i]=read_dm(i)

In [30]:
#Beta bandpass filter from class B
def read_dn(i):
    fs = 250
    lowcut = 12.01
    highcut = 29.99
    beta= butter_bandpass_filter(B[i], lowcut, highcut, fs, order=5)
    beta = np.mean(beta, axis=-1)
    return beta

In [31]:
#getting the shape of the beta of class B
betaB=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
for i in range(0,26):
    betaB[i]=read_dn(i)

In [32]:
#Gamma bandpass filter from class A
def read_dq(i):
    fs = 250
    lowcut = 30.01
    highcut = 100
    gamma= butter_bandpass_filter(A[i], lowcut, highcut, fs, order=5)
    gamma = np.mean(gamma, axis=-1)
    return gamma

In [33]:
#getting the shape of the gamma of class A
gammaA=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
for i in range(0,26):
    gammaA[i]=read_dq(i)

In [34]:
#Gamma bandpass filter from class B
def read_dr(i):
    fs = 250
    lowcut = 30.01
    highcut = 100
    gamma= butter_bandpass_filter(B[i], lowcut, highcut, fs, order=5)
    gamma = np.mean(gamma, axis=-1)
    return gamma

In [35]:
#getting the shape of the gamma of class B
gammaB=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
for i in range(0,26):
    gammaB[i]=read_dr(i)

In [36]:
def calculate_mean_median_features(eeg_signals):
    mean_median_features = []

    for signal in eeg_signals:
        segment_features = []

        for segment in signal:
            mean_feat = np.mean(segment)
            median_feat = np.median(segment)
            
            segment_features.append(mean_feat)
            segment_features.append(median_feat)
        
        mean_median_features.append(segment_features)

    return np.array(mean_median_features)

In [37]:
# Calculate Hjorth parameters for each EEG segment
def hjorth_parameters(eeg_segment):
    activity = np.var(eeg_segment)
    diff_signal = np.diff(eeg_segment)
    mobility = np.var(diff_signal)
    diff2_signal = np.diff(diff_signal)
    complexity = np.var(diff2_signal)
    
    return activity, mobility, complexity

# Calculate Hjorth features for all segments in the EEG signals
def calculate_hjorth_features(eeg_signals):
    hjorth_features = []

    for signal in eeg_signals:
        segment_features = []

        for segment in signal:
            hjorth_feats = hjorth_parameters(segment)
            segment_features.extend(hjorth_feats)
        
        hjorth_features.append(segment_features)

    return np.array(hjorth_features)

In [91]:
A[0][0][0]

array([0.4070568 , 0.37980493, 0.47934596, ..., 0.07075923, 0.09609868,
       0.08749283])

In [84]:
def shannon_entropy(signal):
    # Compute the histogram of the signal
    hist, _ = np.histogram(signal, bins=256, range=(0, 256))
    
    # Normalize the histogram
    hist = hist / (len(signal) * 1.0)
    #print(hist)
    # Calculate Shannon entropy
    entropy = -np.sum([p * np.log2(p + np.finfo(float).eps) for p in hist if p > 0])
    
    return entropy

def calculate_shannon_entropy_features(eeg_signals):
    shannon_entropy_features = []

    for signal in eeg_signals:
        segment_features = []

        for segment in signal:
            entropy_feat = shannon_entropy(segment)
            segment_features.append(entropy_feat)
        
        shannon_entropy_features.append(segment_features)

    return np.array(shannon_entropy_features)

In [39]:
#!pip install PyWavelets

In [97]:
signal=A[0][0][0]
# Compute the histogram of the signal
hist, _ = np.histogram(signal, bins=256, range=(0, 256))
    
# Normalize the histogram
hist = hist / (len(signal) * 1.0)
#print(hist)
# Calculate Shannon entropy
entropy = -np.sum([p * np.log2(p + np.finfo(float).eps) for p in hist if p > 0])
print(entropy)

0.010283343991908014


In [40]:
import pywt

def calculate_wavelet_features(eeg_signals, wavelet='db4', level=4):
    wavelet_features = []

    for signal in eeg_signals:
        segment_features = []

        for segment in signal:
            # Apply discrete wavelet transform
            coeffs = pywt.wavedec(segment, wavelet, level=level)
            
            # Extract the approximation and detail coefficients
            approx = coeffs[0]
            details = np.concatenate(coeffs[1:])
            
            # Calculate statistical features (mean, variance, etc.) on coefficients
            mean = np.mean(details)
            variance = np.var(details)
            energy = np.sum(np.square(details))
            
            # Append wavelet features for this segment
            segment_features.extend([mean, variance, energy])
        
        wavelet_features.append(segment_features)

    return np.array(wavelet_features)

In [41]:
#!pip install scipy

In [42]:
from scipy.stats import skew, kurtosis

def calculate_skewness_kurtosis_features(eeg_signals):
    skewness_features = []
    kurtosis_features = []

    for signal in eeg_signals:
        segment_skewness = []
        segment_kurtosis = []

        for segment in signal:
            # Calculate skewness and kurtosis for each segment
            skew_val = skew(segment)
            kurtosis_val = kurtosis(segment)

            segment_skewness.append(skew_val)
            segment_kurtosis.append(kurtosis_val)

        # Append skewness and kurtosis features for this signal
        skewness_features.append(segment_skewness)
        kurtosis_features.append(segment_kurtosis)

    return np.array(skewness_features), np.array(kurtosis_features)

# Example usage:
# Assuming eeg_signals is a list of EEG signal segments, where each segment is a 1D numpy array.


In [43]:
meanmedianA=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
meanmedianB=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
hjorthA=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
hjorthB=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
shanon_A=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
shanon_B=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
wavelet_features_A=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
wavelet_features_B=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
skewnessA=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
skewnessB=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
kurtosisA=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
kurtosisB=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
for i in range(0,26):
    meanmedianA[i]=calculate_mean_median_features(A[i])
    meanmedianB[i]=calculate_mean_median_features(B[i])
    hjorthA[i] = calculate_hjorth_features(A[i])
    hjorthB[i] = calculate_hjorth_features(B[i])
    shanon_A[i] = calculate_shannon_entropy_features(A[i])
    shanon_B[i] = calculate_shannon_entropy_features(B[i])
    wavelet_features_A[i] = calculate_wavelet_features(A[i])
    wavelet_features_B[i] = calculate_wavelet_features(B[i])
    skewnessA[i], kurtosisA[i] = calculate_skewness_kurtosis_features(A[i])
    skewnessB[i], kurtosisB[i] = calculate_skewness_kurtosis_features(B[i])

In [180]:
print(shanon_B[1])

[[0.01028334 0.01028334 0.01028334]
 [0.01028334 0.01028334 0.01028334]
 [0.01028334 0.01028334 0.01028334]
 [0.01028334 0.01028334 0.01028334]
 [0.01028334 0.01028334 0.01028334]
 [0.01028334 0.01028334 0.01028334]
 [0.01028334 0.01028334 0.01028334]
 [0.01028334 0.01028334 0.01028334]
 [0.01028334 0.01028334 0.01028334]
 [0.01028334 0.01028334 0.01028334]
 [0.01028334 0.01028334 0.01028334]
 [0.01028334 0.01028334 0.01028334]
 [0.01028334 0.01028334 0.01028334]
 [0.01028334 0.01028334 0.01028334]
 [0.01028334 0.01028334 0.01028334]
 [0.01028334 0.01028334 0.01028334]
 [0.01028334 0.01028334 0.01028334]
 [0.01028334 0.01028334 0.01028334]
 [0.01028334 0.01028334 0.01028334]
 [0.01028334 0.01878935 0.01028334]
 [0.01028334 0.01028334 0.01028334]
 [0.01028334 0.01028334 0.01028334]
 [0.01028334 0.01028334 0.01028334]
 [0.01028334 0.01028334 0.01028334]
 [0.01028334 0.01028334 0.01028334]
 [0.01028334 0.01028334 0.01028334]
 [0.01028334 0.01028334 0.01028334]
 [0.01028334 0.01028334 0.01

In [44]:
#total data for delta feature of class A and B
deltaallA=[]
deltaallB=[]
for i in range(0,26):
    deltaallA=np.append(deltaallA,deltaA[i])
    deltaallB=np.append(deltaallB,deltaB[i])
deltaallA=deltaallA.reshape(2080,3)
deltaallB=deltaallB.reshape(2080,3)
deltaallB.shape

(2080, 3)

In [45]:
#total data of delta feature
aDelta=np.append(deltaallA,deltaallB)
aDelta=aDelta.reshape(4160,3)
aDelta.shape

(4160, 3)

In [46]:
#total data for delta feature of class A and B
thetaallA=[]
thetaallB=[]
for i in range(0,26):
    thetaallA=np.append(thetaallA,thetaA[i])
    thetaallB=np.append(thetaallB,thetaB[i])
thetaallA=thetaallA.reshape(2080,3)
thetaallB=thetaallB.reshape(2080,3)
atheta=np.append(thetaallA,thetaallB)
atheta=atheta.reshape(4160,3)
atheta.shape

(4160, 3)

In [47]:
minatheta = np.min(atheta, axis=0, keepdims=True)
maxatheta = np.max(atheta, axis=0, keepdims=True)
atheta= (atheta- minatheta) / (maxatheta - minatheta)

In [48]:
#total data for delta feature of class A and B
alphaallA=[]
alphaallB=[]
for i in range(0,26):
    alphaallA=np.append(alphaallA,alphaA[i])
    alphaallB=np.append(alphaallB,alphaB[i])
alphaallA=alphaallA.reshape(2080,3)
alphaallB=alphaallB.reshape(2080,3)
alphaAll=np.append(alphaallA,alphaallB)
alphaAll=alphaAll.reshape(4160,3)
alphaAll.shape

(4160, 3)

In [49]:
minalphaAll = np.min(alphaAll, axis=0, keepdims=True)
maxalphaAll = np.max(alphaAll, axis=0, keepdims=True)
alphaAll= (alphaAll - minalphaAll) / (maxalphaAll - minalphaAll)

In [50]:
#total data for delta feature of class A and B
betaallA=[]
betaallB=[]
for i in range(0,26):
    betaallA=np.append(betaallA,betaA[i])
    betaallB=np.append(betaallB,betaB[i])
betaallA=betaallA.reshape(2080,3)
betaallB=betaallB.reshape(2080,3)
abeta=np.append(betaallA,betaallB)
abeta=abeta.reshape(4160,3)
abeta.shape

(4160, 3)

In [51]:
minabeta = np.min(abeta, axis=0, keepdims=True)
maxabeta = np.max(abeta, axis=0, keepdims=True)
abeta= (abeta - minabeta) / (maxabeta - minabeta)

In [52]:
#total data for delta feature of class A and B
gammaallA=[]
gammaallB=[]
for i in range(0,26):
    gammaallA=np.append(gammaallA,gammaA[i])
    gammaallB=np.append(gammaallB,gammaB[i])
gammaallA=gammaallA.reshape(2080,3)
gammaallB=gammaallB.reshape(2080,3)
agamma=np.append(gammaallA,gammaallB)
agamma=agamma.reshape(4160,3)
agamma.shape

(4160, 3)

In [53]:
minagamma = np.min(agamma, axis=0, keepdims=True)
maxagamma = np.max(agamma, axis=0, keepdims=True)
agamma= (agamma - minagamma) / (maxagamma - minagamma)

In [54]:
#total data for delta feature of class A and B
hjorthallA=[]
hjorthallB=[]
for i in range(0,26):
    hjorthallA=np.append(hjorthallA,hjorthA[i])
    hjorthallB=np.append(hjorthallB,hjorthB[i])
hjorthallA=hjorthallA.reshape(2080,9)
hjorthallB=hjorthallB.reshape(2080,9)
ahjorth=np.append(hjorthallA,hjorthallB)
ahjorth=ahjorth.reshape(4160,9)
ahjorth.shape

(4160, 9)

In [55]:
#total data for delta feature of class A and B
meanmedianallA=[]
meanmedianallB=[]
for i in range(0,26):
    meanmedianallA=np.append(meanmedianallA,meanmedianA[i])
    meanmedianallB=np.append(meanmedianallB,meanmedianB[i])
meanmedianallA=meanmedianallA.reshape(2080,6)
meanmedianallB=meanmedianallB.reshape(2080,6)
ameanmedian=np.append(meanmedianallA,meanmedianallB)
ameanmedian=ameanmedian.reshape(4160,6)
ameanmedian.shape

(4160, 6)

In [56]:
#total data for delta feature of class A and B
shanonallA=[]
shanonallB=[]
for i in range(0,26):
    shanonallA=np.append(shanonallA,shanon_A[i])
    shanonallB=np.append(shanonallB,shanon_B[i])
shanonallA=shanonallA.reshape(2080,3)
shanonallB=shanonallB.reshape(2080,3)
ashanon=np.append(shanonallA,shanonallB)
ashanon=ashanon.reshape(4160,3)
ashanon.shape

(4160, 3)

In [57]:
#total data for delta feature of class A and B
wavelet_featuresallA=[]
wavelet_featuresallB=[]
for i in range(0,26):
    wavelet_featuresallA=np.append(wavelet_featuresallA,wavelet_features_A[i])
    wavelet_featuresallB=np.append(wavelet_featuresallB,wavelet_features_B[i])
wavelet_featuresallA=wavelet_featuresallA.reshape(2080,9)
wavelet_featuresallB=wavelet_featuresallB.reshape(2080,9)
awavelet_features=np.append(wavelet_featuresallA,wavelet_featuresallB)
awavelet_features=awavelet_features.reshape(4160,9)
awavelet_features.shape

(4160, 9)

In [58]:
minWavelet = np.min(awavelet_features, axis=0, keepdims=True)
maxWavelet = np.max(awavelet_features, axis=0, keepdims=True)
awavelet_features= (awavelet_features - minWavelet) / (maxWavelet - minWavelet)

In [59]:
#total data for delta feature of class A and B
skewnessallA=[]
skewnessallB=[]
for i in range(0,26):
    skewnessallA=np.append(skewnessallA,skewnessA[i])
    skewnessallB=np.append(skewnessallB,skewnessB[i])
skewnessallA=skewnessallA.reshape(2080,3)
skewnessallB=skewnessallB.reshape(2080,3)
askewness=np.append(skewnessallA,skewnessallB)
askewness=askewness.reshape(4160,3)
askewness.shape

(4160, 3)

In [60]:
#total data for delta feature of class A and B
kurtosisallA=[]
kurtosisallB=[]
for i in range(0,26):
    kurtosisallA=np.append(kurtosisallA,kurtosisA[i])
    kurtosisallB=np.append(kurtosisallB,kurtosisB[i])
kurtosisallA=kurtosisallA.reshape(2080,3)
kurtosisallB=kurtosisallB.reshape(2080,3)
akurtosis=np.append(kurtosisallA,kurtosisallB)
akurtosis=akurtosis.reshape(4160,3)
akurtosis.shape

(4160, 3)

In [61]:
otherData=np.column_stack((aDelta,atheta,alphaAll,abeta,agamma,ahjorth,ameanmedian,ashanon,awavelet_features,askewness, akurtosis))
otherData.shape

(4160, 48)

In [62]:
xpother=np.empty(4160,dtype=int)

In [63]:
for i in range(0,2080):
    xpother[i]=0
for i in range(2080,4160):
    xpother[i]=1
xpother.shape

(4160,)

In [64]:
'''from sklearn.preprocessing import StandardScaler
ac=StandardScaler()
x_train=ac.fit_transform(x_train)
x_test=ac.transform(x_test)'''

'from sklearn.preprocessing import StandardScaler\nac=StandardScaler()\nx_train=ac.fit_transform(x_train)\nx_test=ac.transform(x_test)'

In [65]:
for i in range(3,30):
    from sklearn.model_selection import train_test_split
    from sklearn.neighbors import KNeighborsClassifier 
    x_train,x_test,y_train,y_test=train_test_split(otherData,xpother,test_size=0.1,stratify=xpother,random_state=0)
    classknn=KNeighborsClassifier(n_neighbors=i,metric='minkowski',p=2)
    classknn.fit(x_train,y_train)
    y_pred=classknn.predict(x_test)
    from sklearn.metrics import confusion_matrix, accuracy_score
    cm= confusion_matrix(y_test, y_pred)
    print(cm)
    print(accuracy_score(y_test,y_pred))


[[178  30]
 [ 49 159]]
0.8100961538461539
[[201   7]
 [ 57 151]]
0.8461538461538461
[[196  12]
 [ 54 154]]
0.8413461538461539
[[206   2]
 [ 62 146]]
0.8461538461538461
[[200   8]
 [ 58 150]]
0.8413461538461539
[[206   2]
 [ 63 145]]
0.84375
[[202   6]
 [ 57 151]]
0.8485576923076923
[[205   3]
 [ 65 143]]
0.8365384615384616
[[203   5]
 [ 61 147]]
0.8413461538461539
[[206   2]
 [ 63 145]]
0.84375
[[204   4]
 [ 61 147]]
0.84375
[[205   3]
 [ 65 143]]
0.8365384615384616
[[203   5]
 [ 62 146]]
0.8389423076923077
[[206   2]
 [ 65 143]]
0.8389423076923077
[[203   5]
 [ 63 145]]
0.8365384615384616
[[207   1]
 [ 64 144]]
0.84375
[[205   3]
 [ 63 145]]
0.8413461538461539
[[206   2]
 [ 64 144]]
0.8413461538461539
[[206   2]
 [ 64 144]]
0.8413461538461539
[[207   1]
 [ 64 144]]
0.84375
[[206   2]
 [ 63 145]]
0.84375
[[206   2]
 [ 64 144]]
0.8413461538461539
[[205   3]
 [ 64 144]]
0.8389423076923077
[[206   2]
 [ 64 144]]
0.8413461538461539
[[205   3]
 [ 63 145]]
0.8413461538461539
[[206   2]
 [ 65

In [66]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(otherData,xpother,test_size=0.1,stratify=xpother,random_state=0)

In [67]:
from sklearn.neighbors import KNeighborsClassifier 
classknn=KNeighborsClassifier(n_neighbors=3,metric='minkowski',p=2)
classknn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [68]:
y_pred=classknn.predict(x_test)

In [69]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test,y_pred))


[[178  30]
 [ 49 159]]
0.8100961538461539


In [70]:
from sklearn.metrics import precision_score, recall_score, f1_score, cohen_kappa_score

# Assuming you have true labels (y_true) and predicted labels (y_pred)
# Replace y_true and y_pred with your actual data

# Calculate precision
precision = precision_score(y_test, y_pred, average='weighted')  # You can change the average parameter

# Calculate recall
recall = recall_score(y_test, y_pred, average='weighted')  # You can change the average parameter

# Calculate F1-score
f1 = f1_score(y_test, y_pred, average='weighted')  # You can change the average parameter

kappa = cohen_kappa_score(y_test, y_pred)


# Print the resultsprint(f"Cohen's Kappa: {kappa}")
print("Cohen's Kappa:", kappa)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:",f1)

Cohen's Kappa: 0.6201923076923077
Precision: 0.8127054052164184
Recall: 0.8100961538461539
F1-score: 0.8096991806363819


In [71]:
#mic feature selection and checking accuracy score and confusion matrix for each no of selected feature
from sklearn.model_selection import GridSearchCV, train_test_split
from scipy.stats import pearsonr
from sklearn.metrics import confusion_matrix, accuracy_score
#from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier 
mic_scores = []
selected_features=[]

acc_scores=[]
def calculate_MIC(x, y):
    # Calculate Pearson correlation coefficient (r) between x and y
    r, _ = pearsonr(x, y)
    
    # Calculate MIC using the formula MIC = |r| * log2(n)
    n = len(x)
    mic = abs(r) * np.log2(n)
    
    return mic

for i in range(0,47):
    #mine.compute_score(x_train[:, feature_idx], y_train)
    mic_score = calculate_MIC(otherData[:, i], xpother)
    #mic_score = mic(otherData[:, i], xpother)
    mic_scores.append(mic_score)


# Sort features based on MIC scores (in descending order)
sorted_features = np.argsort(mic_scores)[::-1]

# Select the top 20 features
for i in range(2,47):
    top_20_features = sorted_features[:i]
    top_20_feature_values = otherData[:, top_20_features]
    
    x_train,x_test,y_train,y_test=train_test_split(top_20_feature_values,xpother,test_size=0.1,stratify=xpother,random_state=0)
   
    for j in range(3,20):
        classknn=KNeighborsClassifier(n_neighbors=j,metric='minkowski',p=2)
        classknn.fit(x_train,y_train)
        y_pred=classknn.predict(x_test)
        cm= confusion_matrix(y_test, y_pred)
        acc_score=accuracy_score(y_test,y_pred)
        acc_scores.append(acc_score)
        #if(accuracy_score(y_test,y_pred)>0.82):
        #print("No of Feature selected and neighbour selected :",i,j)
        #print(accuracy_score(y_test,y_pred))
        #print(cm)
sorted_acc_scores = np.argsort(mic_scores)[::-1]

In [ ]:
mic_scores

[0.31472562609018434,
 0.2957354074137527,
 0.5561643070203897,
 0.06642356756086437,
 0.38977663602222856,
 0.034130294187496905,
 0.24245122947151423,
 0.31263126674274927,
 0.10181718831833828,
 0.17650982676413401,
 0.4369779193099377,
 0.22958782332020494,
 0.0644707937364773,
 0.2691548073863767,
 0.1246047530467868,
 7.848050500987728,
 3.9511647590117085,
 3.204440964920828,
 8.203122026026477,
 6.400225222058534,
 5.175188398440519,
 7.862581034228132,
 4.518607129791445,
 3.7017526955738322,
 8.413634942315536,
 8.352974548639622,
 8.523260858391966,
 8.493519695639991,
 8.384354321490575,
 8.322390651526508,
 7.292795062108749,
 7.4993375698754985,
 7.422145657073783,
 0.024978889758909342,
 6.940417551913325,
 6.939976188013205,
 0.05091929339237251,
 7.352829700224831,
 7.352482026559234,
 0.24645873642801305,
 6.891042017680691,
 6.891077320546602,
 0.22951979072161396,
 0.438357371852728,
 0.29085531505679807,
 0.4099064319123218,
 0.4184893843355919]

In [72]:
#Selected features after mic
for i in range(0,25):
    print(sorted_acc_scores[i])

26
27
24
28
25
29
18
21
15
31
32
37
38
30
34
35
41
40
19
20
22
16
23
17
2


In [185]:
#Highest accuracy gained after feature selection using knn
top_20_features = sorted_features[:25]
top_20_feature_values = otherData[:, top_20_features]
#column_25 = top_20_feature_values[:,24] 
#column_25=column_25.reshape(-1, 1) 
#train-test
x_train,x_test,y_train,y_test=train_test_split(top_20_feature_values,xpother,test_size=0.1,stratify=xpother,random_state=0)
#classification
classknn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classknn.fit(x_train,y_train)
#prediction
y_pred=classknn.predict(x_test)
#confusion matrix
cm= confusion_matrix(y_test, y_pred)
print("No of Feature selected :25 and no of neighbours 5")
print(cm)
print(accuracy_score(y_test,y_pred))

No of Feature selected :25 and no of neighbours 5
[[189  19]
 [ 51 157]]
0.8317307692307693


In [186]:
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
#from sklearn.preprocessing import StandardScaler

# Assuming you have features (X) and labels (y)
# X is a 2D array where each row represents a sample, and each column is a feature
# y is a 1D array containing the labels corresponding to each sample

# Define the number of splits for cross-validation
num_splits = 10

# Initialize the KFold cross-validator
kf = KFold(n_splits=num_splits, shuffle=True, random_state=0)

# Initialize a K-Nearest Neighbors classifier
knn = KNeighborsClassifier(n_neighbors=5)

# Standardize the features using StandardScaler
#scaler = StandardScaler()

# Store the accuracy scores for each fold
accuracy_scores = []

for train_index, test_index in kf.split(column_25):
    # Split the data into training and testing sets
    X_train, X_test = column_25[train_index],column_25[test_index]
    y_train, y_test = xpother[train_index], xpother[test_index]

    # Standardize the features (fit on training data and transform both training and testing data)
    #X_train_std = scaler.fit_transform(X_train)
    #X_test_std = scaler.transform(X_test)

    # Train the classifier on the training data
    knn.fit(X_train, y_train)

    # Make predictions on the testing data
    y_pred = knn.predict(X_test)

    # Calculate and store the accuracy score for this fold
    accuracy = accuracy_score(y_test, y_pred)
    accuracy_scores.append(accuracy)

# Print the accuracy scores for each fold
for i, acc in enumerate(accuracy_scores):
    print(f'Fold {i+1} Accuracy: {acc}')

# Calculate and print the average accuracy across all folds
average_accuracy = np.mean(accuracy_scores)
print(f'Average Accuracy: {average_accuracy}')



Fold 1 Accuracy: 0.8245192307692307
Fold 2 Accuracy: 0.8197115384615384
Fold 3 Accuracy: 0.8052884615384616
Fold 4 Accuracy: 0.8149038461538461
Fold 5 Accuracy: 0.8100961538461539
Fold 6 Accuracy: 0.8221153846153846
Fold 7 Accuracy: 0.8365384615384616
Fold 8 Accuracy: 0.7956730769230769
Fold 9 Accuracy: 0.8485576923076923
Fold 10 Accuracy: 0.8125
Average Accuracy: 0.8189903846153846


In [140]:
from sklearn.metrics import precision_score, recall_score, f1_score, cohen_kappa_score

# Assuming you have true labels (y_true) and predicted labels (y_pred)
# Replace y_true and y_pred with your actual data

# Calculate precision
precision = precision_score(y_test, y_pred, average='weighted')  # You can change the average parameter

# Calculate recall
recall = recall_score(y_test, y_pred, average='weighted')  # You can change the average parameter

# Calculate F1-score
f1 = f1_score(y_test, y_pred, average='weighted')  # You can change the average parameter

kappa = cohen_kappa_score(y_test, y_pred)

print("Cohen's Kappa:", kappa)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:",f1)

Cohen's Kappa: 0.5713028576721781
Precision: 0.7961196467121365
Recall: 0.7860576923076923
F1-score: 0.7839620931207432
