In [1]:
#Importing modules
import os
import mne
import numpy as np
import pandas as df
from scipy.signal import butter, lfilter
from scipy.signal import freqz



In [2]:
#dropping the eog channels working only on 22 eeg channels of 9 files
file_paths_1 = [
    'A01T.gdf',
    'A02T.gdf',
    'A03T.gdf',
    
    'A05T.gdf',
    'A06T.gdf',
    'A07T.gdf',
    'A08T.gdf',
    'A09T.gdf'
]
raw = []

for file_path in file_paths_1:
    raw_data = mne.io.read_raw_gdf(file_path,preload=True, eog=['EOG-left', 'EOG-central', 'EOG-right'])
    
    p=raw_data.drop_channels(['EOG-left', 'EOG-central', 'EOG-right'])
    raw.append(p)


Extracting EDF parameters from C:\Users\DEBMALYA\OneDrive\Desktop\Work\A01T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG-Fz, EEG, EEG, EEG, EEG, EEG, EEG, EEG-C3, EEG, EEG-Cz, EEG, EEG-C4, EEG, EEG, EEG, EEG, EEG, EEG, EEG, EEG-Pz, EEG, EEG
Creating raw.info structure...


C:\Users\DEBMALYA\anaconda3\Lib\contextlib.py:144: RuntimeWarning: Channel names are not unique, found duplicates for: {'EEG'}. Applying running numbers for duplicates.
  next(self.gen)


Reading 0 ... 672527  =      0.000 ...  2690.108 secs...
Extracting EDF parameters from C:\Users\DEBMALYA\OneDrive\Desktop\Work\A02T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG-Fz, EEG, EEG, EEG, EEG, EEG, EEG, EEG-C3, EEG, EEG-Cz, EEG, EEG-C4, EEG, EEG, EEG, EEG, EEG, EEG, EEG, EEG-Pz, EEG, EEG
Creating raw.info structure...
Reading 0 ... 677168  =      0.000 ...  2708.672 secs...


C:\Users\DEBMALYA\anaconda3\Lib\contextlib.py:144: RuntimeWarning: Channel names are not unique, found duplicates for: {'EEG'}. Applying running numbers for duplicates.
  next(self.gen)


Extracting EDF parameters from C:\Users\DEBMALYA\OneDrive\Desktop\Work\A03T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG-Fz, EEG, EEG, EEG, EEG, EEG, EEG, EEG-C3, EEG, EEG-Cz, EEG, EEG-C4, EEG, EEG, EEG, EEG, EEG, EEG, EEG, EEG-Pz, EEG, EEG
Creating raw.info structure...
Reading 0 ... 660529  =      0.000 ...  2642.116 secs...


C:\Users\DEBMALYA\anaconda3\Lib\contextlib.py:144: RuntimeWarning: Channel names are not unique, found duplicates for: {'EEG'}. Applying running numbers for duplicates.
  next(self.gen)


Extracting EDF parameters from C:\Users\DEBMALYA\OneDrive\Desktop\Work\A05T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG-Fz, EEG, EEG, EEG, EEG, EEG, EEG, EEG-C3, EEG, EEG-Cz, EEG, EEG-C4, EEG, EEG, EEG, EEG, EEG, EEG, EEG, EEG-Pz, EEG, EEG
Creating raw.info structure...
Reading 0 ... 686119  =      0.000 ...  2744.476 secs...


C:\Users\DEBMALYA\anaconda3\Lib\contextlib.py:144: RuntimeWarning: Channel names are not unique, found duplicates for: {'EEG'}. Applying running numbers for duplicates.
  next(self.gen)


Extracting EDF parameters from C:\Users\DEBMALYA\OneDrive\Desktop\Work\A06T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG-Fz, EEG, EEG, EEG, EEG, EEG, EEG, EEG-C3, EEG, EEG-Cz, EEG, EEG-C4, EEG, EEG, EEG, EEG, EEG, EEG, EEG, EEG-Pz, EEG, EEG
Creating raw.info structure...
Reading 0 ... 678979  =      0.000 ...  2715.916 secs...


C:\Users\DEBMALYA\anaconda3\Lib\contextlib.py:144: RuntimeWarning: Channel names are not unique, found duplicates for: {'EEG'}. Applying running numbers for duplicates.
  next(self.gen)


Extracting EDF parameters from C:\Users\DEBMALYA\OneDrive\Desktop\Work\A07T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG-Fz, EEG, EEG, EEG, EEG, EEG, EEG, EEG-C3, EEG, EEG-Cz, EEG, EEG-C4, EEG, EEG, EEG, EEG, EEG, EEG, EEG, EEG-Pz, EEG, EEG
Creating raw.info structure...
Reading 0 ... 681070  =      0.000 ...  2724.280 secs...


C:\Users\DEBMALYA\anaconda3\Lib\contextlib.py:144: RuntimeWarning: Channel names are not unique, found duplicates for: {'EEG'}. Applying running numbers for duplicates.
  next(self.gen)


Extracting EDF parameters from C:\Users\DEBMALYA\OneDrive\Desktop\Work\A08T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG-Fz, EEG, EEG, EEG, EEG, EEG, EEG, EEG-C3, EEG, EEG-Cz, EEG, EEG-C4, EEG, EEG, EEG, EEG, EEG, EEG, EEG, EEG-Pz, EEG, EEG
Creating raw.info structure...
Reading 0 ... 675269  =      0.000 ...  2701.076 secs...


C:\Users\DEBMALYA\anaconda3\Lib\contextlib.py:144: RuntimeWarning: Channel names are not unique, found duplicates for: {'EEG'}. Applying running numbers for duplicates.
  next(self.gen)


Extracting EDF parameters from C:\Users\DEBMALYA\OneDrive\Desktop\Work\A09T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG-Fz, EEG, EEG, EEG, EEG, EEG, EEG, EEG-C3, EEG, EEG-Cz, EEG, EEG-C4, EEG, EEG, EEG, EEG, EEG, EEG, EEG, EEG-Pz, EEG, EEG
Creating raw.info structure...
Reading 0 ... 673327  =      0.000 ...  2693.308 secs...


C:\Users\DEBMALYA\anaconda3\Lib\contextlib.py:144: RuntimeWarning: Channel names are not unique, found duplicates for: {'EEG'}. Applying running numbers for duplicates.
  next(self.gen)


In [3]:
#Annotation object for annotating segments of raw data.
for i in range(0,8):
    raw[i].annotations
    events=mne.events_from_annotations(raw[i])
    #printing the 1st index of the events which contains the overall details of the file
    events[1]

Used Annotations descriptions: ['1023', '1072', '276', '277', '32766', '768', '769', '770', '771', '772']
Used Annotations descriptions: ['1023', '1072', '276', '277', '32766', '768', '769', '770', '771', '772']
Used Annotations descriptions: ['1023', '1072', '276', '277', '32766', '768', '769', '770', '771', '772']
Used Annotations descriptions: ['1023', '1072', '276', '277', '32766', '768', '769', '770', '771', '772']
Used Annotations descriptions: ['1023', '1072', '276', '277', '32766', '768', '769', '770', '771', '772']
Used Annotations descriptions: ['1023', '1072', '276', '277', '32766', '768', '769', '770', '771', '772']
Used Annotations descriptions: ['1023', '1072', '276', '277', '32766', '768', '769', '770', '771', '772']
Used Annotations descriptions: ['1023', '1072', '276', '277', '32766', '768', '769', '770', '771', '772']


In [4]:
#getting the rawinfo(information of each file)
rawinfo=[]
for i in range(0,8):
    rawinfo=np.append(rawinfo,raw[i].info)

In [5]:
rawinfo[0].ch_names

['EEG-Fz',
 'EEG-0',
 'EEG-1',
 'EEG-2',
 'EEG-3',
 'EEG-4',
 'EEG-5',
 'EEG-C3',
 'EEG-6',
 'EEG-Cz',
 'EEG-7',
 'EEG-C4',
 'EEG-8',
 'EEG-9',
 'EEG-10',
 'EEG-11',
 'EEG-12',
 'EEG-13',
 'EEG-14',
 'EEG-Pz',
 'EEG-15',
 'EEG-16']

In [6]:
#creating a event dictionary
event_dict={
 'reject':1,
 'eye move':2,
 'eye open':3,
 'eye close':4,
 'new run':5,
 'new trial':6,
 'class 1':7,
 'class 2':8,
 'class 3':9,
 'class 4':10,
}

In [7]:
#taking classA of 9 subjects
classA=[0,0,0,0,0,0,0,0]
for i in range(0,8):
    epochs = mne.Epochs(raw[i], events[0], event_id=[7], tmin=0.0, tmax=5.9, baseline=(0, 0), preload=True)
    classA[i] = epochs.copy().crop(tmin=2.0, tmax=5.9).get_data() 

Not setting metadata
72 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 72 events and 1476 original time points ...
0 bad epochs dropped
Not setting metadata
72 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 72 events and 1476 original time points ...
0 bad epochs dropped
Not setting metadata
72 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 72 events and 1476 original time points ...
1 bad epochs dropped
Not setting metadata
72 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 72 events and 1476 original time points ...
0 bad epochs dropped
Not setting metadata
72 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from pre

In [8]:
#taking classB of 9 subjects
classB=[0,0,0,0,0,0,0,0]
for i in range(0,8):
    epochs = mne.Epochs(raw[i], events[0], event_id=[8], tmin=0.0, tmax=5.9, baseline=(0, 0), preload=True)
    classB[i] = epochs.copy().crop(tmin=2.0, tmax=5.9).get_data() 

Not setting metadata
72 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 72 events and 1476 original time points ...
0 bad epochs dropped
Not setting metadata
72 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 72 events and 1476 original time points ...
0 bad epochs dropped
Not setting metadata
72 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 72 events and 1476 original time points ...
2 bad epochs dropped
Not setting metadata
72 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 72 events and 1476 original time points ...
0 bad epochs dropped
Not setting metadata
72 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from pre

In [9]:
for i in range(0,8):
    print(classB[i].shape)

(72, 22, 976)
(72, 22, 976)
(70, 22, 976)
(72, 22, 976)
(72, 22, 976)
(72, 22, 976)
(72, 22, 976)
(72, 22, 976)


In [10]:
#converting the classA to epochsArray
A=[0,0,0,0,0,0,0,0]
for i in range(0,8):
    A[i]=mne.EpochsArray(classA[i],rawinfo[i])

Not setting metadata
72 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
72 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
71 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
72 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
72 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
72 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
72 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
72 matching events found
No baseline correction applied
0 projection items activated


In [11]:
#converting the classB to epochsArray
B=[0,0,0,0,0,0,0,0]
for i in range(0,8):
    B[i]=mne.EpochsArray(classB[i],rawinfo[i])

Not setting metadata
72 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
72 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
70 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
72 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
72 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
72 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
72 matching events found
No baseline correction applied
0 projection items activated
Not setting metadata
72 matching events found
No baseline correction applied
0 projection items activated


In [12]:
for i in range(0,8):
    min_val = np.min(A[i], axis=2, keepdims=True)
    max_val = np.max(A[i], axis=2, keepdims=True)
    A[i] = (A[i] - min_val) / (max_val - min_val)


In [13]:
for i in range(0,3):
    min_val = np.min(B[i], axis=2, keepdims=True)
    max_val = np.max(B[i], axis=2, keepdims=True)
    B[i] = (B[i] - min_val) / (max_val - min_val)

In [14]:
#building the bandpass filter function
def butter_bandpass_filter(signal, lowcut, highcut, fs, order=5):
    nyq = 0.5 * fs
    low = lowcut/nyq
    high = highcut/nyq
    b,a = butter(order, [low, high], btype='band')
    y = lfilter(b, a, signal, axis=-1)
    
    return y

In [15]:
#delta bandpass filter from class A
def read_da(i):
    fs = 250
    lowcut = 0.5
    highcut = 3.99
    delta= butter_bandpass_filter(A[i], lowcut, highcut, fs, order=5)
    delta = np.mean(delta, axis=-1)
    return delta

In [16]:
#calling the function for delta of classA separately for each files
deltaA=[0,0,0,0,0,0,0,0]
for i in range(0,8):
    deltaA[i]=read_da(i)


In [17]:
#delta bandpass filter from class B
def read_db(i):
    fs = 250
    lowcut = 0.5
    highcut = 3.99
    delta= butter_bandpass_filter(B[i], lowcut, highcut, fs, order=5)
    delta = np.mean(delta, axis=-1)
    return delta

In [18]:
#calling the function for delta of classB separately for each files
deltaB=[0,0,0,0,0,0,0,0] 
for i in range(0,8):
    deltaB[i]=read_db(i)

In [19]:
#theta bandpass filter from class A
def read_de(i):
    fs = 250
    lowcut = 4
    highcut = 7.99
    theta= butter_bandpass_filter(A[i], lowcut, highcut, fs, order=5)
    theta = np.mean(theta, axis=-1)
    return theta

In [20]:
#calling the function for theta of classA separately for each files
thetaA=[0,0,0,0,0,0,0,0]
for i in range(0,8):
    thetaA[i]=read_de(i)

In [21]:
#Theta bandpass filter from class B
def read_df(i):
    fs = 250
    lowcut = 4
    highcut = 7.99
    theta= butter_bandpass_filter(B[i], lowcut, highcut, fs, order=5)
    theta = np.mean(theta, axis=-1)
    return theta

In [22]:
#calling the function for theta of classB separately for each files
thetaB=[0,0,0,0,0,0,0,0]
for i in range(0,8):
    thetaB[i]=read_df(i)

In [23]:
#Alpha bandpass filter from class A
def read_di(i):
    fs = 250
    lowcut = 8.01
    highcut = 11.99
    alpha= butter_bandpass_filter(A[i], lowcut, highcut, fs, order=5)
    alpha = np.mean(alpha, axis=-1)
    return alpha

In [24]:
#calling the function for alpha of classA separately for each files
alphaA=[0,0,0,0,0,0,0,0]
for i in range(0,8):
    alphaA[i]=read_di(i)

In [25]:
#Alpha bandpass filter from class B
def read_dj(i):
    fs = 250
    lowcut = 8.01
    highcut = 11.99
    alpha= butter_bandpass_filter(B[i], lowcut, highcut, fs, order=5)
    alpha = np.mean(alpha, axis=-1)
    return alpha

In [26]:
#calling the function for alpha of classB separately for each files
alphaB=[0,0,0,0,0,0,0,0]
for i in range(0,8):
    alphaB[i]=read_dj(i)

In [27]:
#Beta bandpass filter from class A
def read_dm(i):
    fs = 250
    lowcut = 12.01
    highcut = 29.99
    beta= butter_bandpass_filter(A[i], lowcut, highcut, fs, order=5)
    beta = np.mean(beta, axis=-1)
    return beta

In [28]:
#calling the function for beta of classA separately for each files
betaA=[0,0,0,0,0,0,0,0]
for i in range(0,8):
    betaA[i]=read_dm(i)

In [29]:
#Beta bandpass filter from class B
def read_dn(i):
    fs = 250
    lowcut = 12.01
    highcut = 29.99
    beta= butter_bandpass_filter(B[i], lowcut, highcut, fs, order=5)
    beta = np.mean(beta, axis=-1)
    return beta

In [30]:
#calling the function for beta of classB separately for each files
betaB=[0,0,0,0,0,0,0,0]
for i in range(0,8):
    betaB[i]=read_dn(i)

In [31]:
#Gamma bandpass filter from class A
def read_dq(i):
    fs = 250
    lowcut = 30.01
    highcut = 100
    gamma= butter_bandpass_filter(A[i], lowcut, highcut, fs, order=5)
    gamma = np.mean(gamma, axis=-1)
    return gamma

In [32]:
#calling the function for gamma of classB separately for each files
gammaA=[0,0,0,0,0,0,0,0]
for i in range(0,8):
    gammaA[i]=read_dq(i)

In [33]:
#Gamma bandpass filter from class B
def read_dr(i):
    fs = 250
    lowcut = 30.01
    highcut = 100
    gamma= butter_bandpass_filter(B[i], lowcut, highcut, fs, order=5)
    gamma = np.mean(gamma, axis=-1)
    return gamma

In [34]:
#calling the function for gamma of classB separately for each files
gammaB=[0,0,0,0,0,0,0,0]
for i in range(0,8):
    gammaB[i]=read_dr(i)

In [35]:
#mean median feature function
def calculate_mean_median_features(eeg_signals):
    mean_median_features = []

    for signal in eeg_signals:
        segment_features = []

        for segment in signal:
            mean_feat = np.mean(segment)
            median_feat = np.median(segment)
            
            segment_features.append(mean_feat)
            segment_features.append(median_feat)
        
        mean_median_features.append(segment_features)

    return np.array(mean_median_features)


In [36]:
#meanmedian feature of class A separately for all subjects
meanmedianA=[0,0,0,0,0,0,0,0]
for i in range(0,8):
    meanmedianA[i]=calculate_mean_median_features(A[i])

In [37]:
#meanmedian feature of class B separately for all subjects
meanmedianB=[0,0,0,0,0,0,0,0]
for i in range(0,8):
    meanmedianB[i]=calculate_mean_median_features(B[i])

In [38]:
# Calculate Hjorth parameters for each EEG segment
def hjorth_parameters(eeg_segment):
    activity = np.var(eeg_segment)
    diff_signal = np.diff(eeg_segment)
    mobility = np.var(diff_signal)
    diff2_signal = np.diff(diff_signal)
    complexity = np.var(diff2_signal)
    
    return activity, mobility, complexity

# Calculate Hjorth features for all segments in the EEG signals
def calculate_hjorth_features(eeg_signals):
    hjorth_features = []

    for signal in eeg_signals:
        segment_features = []

        for segment in signal:
            hjorth_feats = hjorth_parameters(segment)
            segment_features.extend(hjorth_feats)
        
        hjorth_features.append(segment_features)

    return np.array(hjorth_features)

In [39]:
#hjorth feature of class A and classB separately for all subjects
hjorthA=[0,0,0,0,0,0,0,0]
hjorthB=[0,0,0,0,0,0,0,0]
for i in range(0,8):
    hjorthA[i] = calculate_hjorth_features(A[i])
    hjorthB[i] = calculate_hjorth_features(B[i])


In [40]:
#shanon entrophy feature function
def shannon_entropy(signal):
    # Compute the histogram of the signal
    hist, _ = np.histogram(signal, bins=256, range=(0, 256))
    
    # Normalize the histogram
    hist = hist / (len(signal) * 1.0)
    
    # Calculate Shannon entropy
    entropy = -np.sum([p * np.log2(p + np.finfo(float).eps) for p in hist if p > 0])
    
    return entropy

def calculate_shannon_entropy_features(eeg_signals):
    shannon_entropy_features = []

    for signal in eeg_signals:
        segment_features = []

        for segment in signal:
            entropy_feat = shannon_entropy(segment)
            segment_features.append(entropy_feat)
        
        shannon_entropy_features.append(segment_features)

    return np.array(shannon_entropy_features)

In [41]:
#shanon feature of class A separately for all subjects
shanonA=[0,0,0,0,0,0,0,0]
for i in range(0,8):
    shanonA[i]=calculate_shannon_entropy_features(A[i])


In [42]:
#shanon feature of class B separately for all subjects
shanonB=[0,0,0,0,0,0,0,0]
for i in range(0,8):
    shanonB[i]=calculate_shannon_entropy_features(B[i])

In [43]:
#wavelet feature function
import numpy as np
import pywt

def calculate_wavelet_features(eeg_signals, wavelet='db4', level=4):
    wavelet_features = []

    for signal in eeg_signals:
        segment_features = []

        for segment in signal:
            # Apply discrete wavelet transform
            coeffs = pywt.wavedec(segment, wavelet, level=level)
            
            # Extract the approximation and detail coefficients
            approx = coeffs[0]
            details = np.concatenate(coeffs[1:])
            
            # Calculate statistical features (mean, variance, etc.) on coefficients
            mean = np.mean(details)
            variance = np.var(details)
            energy = np.sum(np.square(details))
            
            # Append wavelet features for this segment
            segment_features.extend([mean, variance, energy])
        
        wavelet_features.append(segment_features)

    return np.array(wavelet_features)

In [44]:
#wavelet feature of class A separately for all subjects
waveletA=[0,0,0,0,0,0,0,0]
for i in range(0,8):
    waveletA[i] = calculate_wavelet_features(A[i])

In [45]:
#wavelet feature of class B separately for all subjects
waveletB=[0,0,0,0,0,0,0,0]
for i in range(0,8):
    waveletB[i] = calculate_wavelet_features(B[i])

In [46]:
#skewness and kurtosis feature function
from scipy.stats import skew, kurtosis

def calculate_skewness_kurtosis_features(eeg_signals):
    skewness_features = []
    kurtosis_features = []

    for signal in eeg_signals:
        segment_skewness = []
        segment_kurtosis = []

        for segment in signal:
            # Calculate skewness and kurtosis for each segment
            skew_val = skew(segment)
            kurtosis_val = kurtosis(segment)

            segment_skewness.append(skew_val)
            segment_kurtosis.append(kurtosis_val)

        # Append skewness and kurtosis features for this signal
        skewness_features.append(segment_skewness)
        kurtosis_features.append(segment_kurtosis)

    return np.array(skewness_features), np.array(kurtosis_features)

In [47]:
#skewness,kurtosis feature of class A separately for all subjects
skewnessA=[0,0,0,0,0,0,0,0]
kurtosisA=[0,0,0,0,0,0,0,0]
for i in range(0,8):
    skewnessA[i], kurtosisA[i] = calculate_skewness_kurtosis_features(A[i])

In [48]:
#skewness,kurtosis feature of class A separately for all subjects
skewnessB=[0,0,0,0,0,0,0,0]
kurtosisB=[0,0,0,0,0,0,0,0]
for i in range(0,8):
    skewnessB[i], kurtosisB[i] = calculate_skewness_kurtosis_features(B[i])

In [49]:
#total data for delta feature of class A
deltaallA=[]
for i in range(0,8):
    deltaallA=np.append(deltaallA,deltaA[i]);
deltaallA=deltaallA.reshape(575,22)
deltaallA.shape

(575, 22)

In [50]:
#total data for delta feature of class B
deltaallB=[]
for i in range(0,8):
    deltaallB=np.append(deltaallB,deltaB[i]);
deltaallB=deltaallB.reshape(574,22)
deltaallB.shape

(574, 22)

In [51]:
#total data of delta feature
aDelta=np.append(deltaallA,deltaallB)
aDelta=aDelta.reshape(1149,22)
aDelta.shape

(1149, 22)

In [52]:
#total data for theta feature of class A
thetaallA=[]
for i in range(0,8):
    thetaallA=np.append(thetaallA,thetaA[i])
thetaallA=thetaallA.reshape(575,22)
thetaallA.shape

(575, 22)

In [53]:
#total data for theta feature of class B
thetaallB=[]
for i in range(0,8):
    thetaallB=np.append(thetaallB,thetaB[i])
thetaallB=thetaallB.reshape(574,22)
thetaallB.shape

(574, 22)

In [54]:
#total data for theta feature
aTheta=np.append(thetaallA,thetaallB)
aTheta=aTheta.reshape(1149,22)
aTheta.shape

(1149, 22)

In [55]:
minTheta = np.min(aTheta, axis=1, keepdims=True)
maxTheta = np.max(aTheta, axis=1, keepdims=True)
aTheta = (aTheta - minTheta) / (maxTheta - minTheta)

In [56]:
#total data for alpha feature of class A
alphaallA=[]
for i in range(0,8):
    alphaallA=np.append(alphaallA,alphaA[i])
alphaallA=alphaallA.reshape(575,22)
alphaallA.shape

(575, 22)

In [57]:
#total data for alpha feature of class B
alphaallB=[]
for i in range(0,8):
    alphaallB=np.append(alphaallB,alphaB[i])
alphaallB=alphaallB.reshape(574,22)
alphaallB.shape

(574, 22)

In [58]:
#total data for alpha feature
aAlpha=np.append(alphaallA,alphaallB)
aAlpha=aAlpha.reshape(1149,22)
aAlpha.shape

(1149, 22)

In [59]:
minAlpha = np.min(aAlpha, axis=1, keepdims=True)
maxAlpha = np.max(aAlpha, axis=1, keepdims=True)
aAlpha = (aAlpha - minAlpha) / (maxAlpha - minAlpha)

In [60]:
#total data for beta feature of class A
betaallA=[]
for i in range(0,8):
    betaallA=np.append(betaallA,betaA[i])
betaallA=betaallA.reshape(575,22)
betaallA.shape

(575, 22)

In [61]:
#total data for beta feature of class B
betaallB=[]
for i in range(0,8):
    betaallB=np.append(betaallB,betaB[i])
betaallB=betaallB.reshape(574,22)
betaallB.shape

(574, 22)

In [62]:
#total data for beta feature
aBeta=np.append(betaallA,betaallB)
aBeta=aBeta.reshape(1149,22)
aBeta.shape

(1149, 22)

In [63]:
minBeta = np.min(aBeta, axis=1, keepdims=True)
maxBeta = np.max(aBeta, axis=1, keepdims=True)
aBeta = (aBeta - minBeta) / (maxBeta - minBeta)

In [64]:
#total data for gamma feature of class A
gammaallA=[]
for i in range(0,8):
    gammaallA=np.append(gammaallA,gammaA[i])
gammaallA=gammaallA.reshape(575,22)
gammaallA.shape

(575, 22)

In [65]:
#total data for gamma feature of class B
gammaallB=[]
for i in range(0,8):
    gammaallB=np.append(gammaallB,gammaB[i])
gammaallB=gammaallB.reshape(574,22)
gammaallB.shape

(574, 22)

In [66]:
#total data for gamma feature
aGamma=np.append(gammaallA,gammaallB)
aGamma=aGamma.reshape(1149,22)
aGamma.shape

(1149, 22)

In [67]:
minGamma = np.min(aGamma, axis=1, keepdims=True)
maxGamma = np.max(aGamma, axis=1, keepdims=True)
aGamma = (aGamma - minGamma) / (maxGamma - minGamma)

In [68]:
#total data for meanmedian feature of class A
meanmedianallA=[]
for i in range(0,8):
    meanmedianallA=np.append(meanmedianallA,meanmedianA[i])
meanmedianallA=meanmedianallA.reshape(575,44)
meanmedianallA.shape

(575, 44)

In [69]:
#total data for meanmedian feature of class B
meanmedianallB=[]
for i in range(0,8):
    meanmedianallB=np.append(meanmedianallB,meanmedianB[i])
meanmedianallB=meanmedianallB.reshape(574,44)
meanmedianallB.shape

(574, 44)

In [70]:
#total data for meanmedian feature
meanmedianAll=np.append(meanmedianallA,meanmedianallB)
meanmedianAll=meanmedianAll.reshape(1149,44)
meanmedianAll.shape

(1149, 44)

In [71]:
#total data for hjorth feature of class A
hjorthallA=[]
for i in range(0,8):
    hjorthallA=np.append(hjorthallA,hjorthA[i])
hjorthallA=hjorthallA.reshape(575,66)
hjorthallA.shape

(575, 66)

In [72]:
#total data for hjorth feature of class B
hjorthallB=[]
for i in range(0,8):
    hjorthallB=np.append(hjorthallB,hjorthB[i])
hjorthallB=hjorthallB.reshape(574,66)
hjorthallB.shape

(574, 66)

In [73]:
#total data for hjorth feature
hjorthAll=np.append(hjorthallA,hjorthallB)
hjorthAll=hjorthAll.reshape(1149,66)
hjorthAll.shape

(1149, 66)

In [74]:
#total data for shanon feature of class A
shanonallA=[]
for i in range(0,8):
    shanonallA=np.append(shanonallA,shanonA[i])
shanonallA=shanonallA.reshape(575,22)
shanonallA.shape

(575, 22)

In [75]:
#total data for shanon feature of class B
shanonallB=[]
for i in range(0,8):
    shanonallB=np.append(shanonallB,shanonB[i])
shanonallB=shanonallB.reshape(574,22)
shanonallB.shape

(574, 22)

In [76]:
#total data for shanon feature
shanonAll=np.append(shanonallA,shanonallB)
shanonAll=shanonAll.reshape(1149,22)
shanonAll.shape

(1149, 22)

In [77]:
#total data for wavelet feature of class A
waveletallA=[]
for i in range(0,8):
    waveletallA=np.append(waveletallA,waveletA[i])
waveletallA=waveletallA.reshape(575,66)
waveletallA.shape

(575, 66)

In [78]:
#total data for wavelet feature of class B
waveletallB=[]
for i in range(0,8):
    waveletallB=np.append(waveletallB,waveletB[i])
waveletallB=waveletallB.reshape(574,66)
waveletallB.shape

(574, 66)

In [79]:
#total data for wavelet feature
waveletAll=np.append(waveletallA,waveletallB)
waveletAll=waveletAll.reshape(1149,66)
waveletAll.shape

(1149, 66)

In [80]:
minWavelet = np.min(waveletAll, axis=0, keepdims=True)
maxWavelet = np.max(waveletAll, axis=0, keepdims=True)
waveletAll= (waveletAll - minWavelet) / (maxWavelet - minWavelet)

In [81]:
#total data for skewness feature of class A
skewnessallA=[]
for i in range(0,8):
    skewnessallA=np.append(skewnessallA,skewnessA[i])
skewnessallA=skewnessallA.reshape(575,22)
skewnessallA.shape

(575, 22)

In [82]:
#total data for skewness feature of class B
skewnessallB=[]
for i in range(0,8):
    skewnessallB=np.append(skewnessallB,skewnessB[i])
skewnessallB=skewnessallB.reshape(574,22)
skewnessallB.shape

(574, 22)

In [83]:
#total data for skewness feature
skewnessAll=np.append(skewnessallA,skewnessallB)
skewnessAll=skewnessAll.reshape(1149,22)
skewnessAll.shape

(1149, 22)

In [84]:
#total data for kurtosis feature of class A
kurtosisallA=[]
for i in range(0,8):
    kurtosisallA=np.append(kurtosisallA,kurtosisA[i])
kurtosisallA=kurtosisallA.reshape(575,22)
kurtosisallA.shape

(575, 22)

In [85]:
#total data for kurtosis feature of class B
kurtosisallB=[]
for i in range(0,8):
    kurtosisallB=np.append(kurtosisallB,kurtosisB[i])
kurtosisallB=kurtosisallB.reshape(574,22)
kurtosisallB.shape

(574, 22)

In [86]:
#total data for kurtosis
kurtosisAll=np.append(kurtosisallA,kurtosisallB)
kurtosisAll=kurtosisAll.reshape(1149,22)
kurtosisAll.shape

(1149, 22)

In [87]:
#all data 
aData = np.column_stack((aDelta, aTheta, aAlpha, aBeta, aGamma,hjorthAll,meanmedianAll,shanonAll,waveletAll,skewnessAll, kurtosisAll))
aData.shape

(1149, 352)

In [88]:
#taking an empty array for labels
xpAll=np.empty(1149,dtype=int)

In [89]:
#taking the labels 0 for class A and 1 for class B
for i in range(0,575):
    xpAll[i]=0
for i in range(575,1149):
    xpAll[i]=1
xpAll.shape

(1149,)

In [90]:
aData.shape

(1149, 352)

In [91]:
xpAll.shape

(1149,)

In [92]:
fifth_column = aData[:, 4]
fifth_column.shape
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(fifth_column.reshape(-1, 1),xpAll,test_size=0.2,stratify=xpAll,random_state=0)
#train the model using knn classifier
from sklearn.neighbors import KNeighborsClassifier 
classknn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classknn.fit(x_train,y_train)
y_pred_a=classknn.predict(x_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test, y_pred_a)
print(cm)
print(accuracy_score(y_test,y_pred_a))

[[96 19]
 [42 73]]
0.7347826086956522


In [93]:
sixth_column = aData[:, 304]
six= sixth_column.reshape(-1, 1)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split( six,xpAll,test_size=0.2,stratify=xpAll,random_state=0)
#train the model using knn classifier
from sklearn.neighbors import KNeighborsClassifier 
classknn=KNeighborsClassifier(n_neighbors=4,metric='minkowski',p=2)
classknn.fit(x_train,y_train)
y_pred_b=classknn.predict(x_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test, y_pred_b)
print(cm)
print(accuracy_score(y_test,y_pred_b))

[[110   5]
 [ 43  72]]
0.7913043478260869


In [94]:
seventh_column = aData[:, 295]
seventh_column.shape
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(seventh_column.reshape(-1, 1),xpAll,test_size=0.2,stratify=xpAll,random_state=0)
#train the model using knn classifier
from sklearn.neighbors import KNeighborsClassifier 
classknn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classknn.fit(x_train,y_train)
y_pred_c=classknn.predict(x_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test, y_pred_c)
print(cm)
print(accuracy_score(y_test,y_pred_c))

[[94 21]
 [43 72]]
0.7217391304347827


In [95]:
eight_column = aData[:, 49]
eight_column.shape
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(eight_column.reshape(-1, 1),xpAll,test_size=0.2,stratify=xpAll,random_state=0)
#train the model using knn classifier
from sklearn.neighbors import KNeighborsClassifier 
classknn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classknn.fit(x_train,y_train)
y_pred_d=classknn.predict(x_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test, y_pred_d)
print(cm)
print(accuracy_score(y_test,y_pred_d))

[[50 65]
 [52 63]]
0.49130434782608695


In [96]:
first_column = aData[:, 280]
first_column.shape
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(first_column.reshape(-1, 1),xpAll,test_size=0.2,stratify=xpAll,random_state=0)
#train the model using knn classifier
from sklearn.neighbors import KNeighborsClassifier 
classknn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classknn.fit(x_train,y_train)
y_pred_e=classknn.predict(x_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test, y_pred_e)
print(cm)
print(accuracy_score(y_test,y_pred_e))

[[103  12]
 [ 43  72]]
0.7608695652173914


In [97]:
second_column = aData[:, 259]
second_column.shape
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(second_column.reshape(-1, 1),xpAll,test_size=0.2,stratify=xpAll,random_state=0)
#train the model using knn classifier
from sklearn.neighbors import KNeighborsClassifier 
classknn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classknn.fit(x_train,y_train)
y_pred_f=classknn.predict(x_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test, y_pred_f)
print(cm)
print(accuracy_score(y_test,y_pred_f))

[[105  10]
 [ 38  77]]
0.7913043478260869


In [98]:
third_column = aData[:, 298]
third_column.shape
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(third_column.reshape(-1, 1),xpAll,test_size=0.2,stratify=xpAll,random_state=0)
#train the model using knn classifier
from sklearn.neighbors import KNeighborsClassifier 
classknn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classknn.fit(x_train,y_train)
y_pred_g=classknn.predict(x_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test, y_pred_g)
print(cm)
print(accuracy_score(y_test,y_pred_g))

[[97 18]
 [42 73]]
0.7391304347826086


In [99]:
fourth_column = aData[:, 301]
fourth_column.shape
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(fourth_column.reshape(-1, 1),xpAll,test_size=0.2,stratify=xpAll,random_state=0)
#train the model using knn classifier
from sklearn.neighbors import KNeighborsClassifier 
classknn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classknn.fit(x_train,y_train)
y_pred_h=classknn.predict(x_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test, y_pred_h)
print(cm)
print(accuracy_score(y_test,y_pred_h))

[[101  14]
 [ 40  75]]
0.7652173913043478


In [100]:
ninth_column = aData[:, 126]
ninth_column.shape
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(ninth_column.reshape(-1, 1),xpAll,test_size=0.2,stratify=xpAll,random_state=0)
#train the model using knn classifier
from sklearn.neighbors import KNeighborsClassifier 
classknn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classknn.fit(x_train,y_train)
y_pred_i=classknn.predict(x_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test, y_pred_h)
print(cm)
print(accuracy_score(y_test,y_pred_h))

[[101  14]
 [ 40  75]]
0.7652173913043478


In [101]:
allX=np.column_stack((y_pred_a,y_pred_b,y_pred_c,y_pred_d,y_pred_e,y_pred_f,y_pred_g,y_pred_h,y_pred_i))

In [102]:
allX.shape

(230, 9)

In [103]:
al=np.empty(230)

In [104]:
for i in range(0,230):
    count=0
    countp=0
    for j in range(0,9):
        if(allX[i][j]==0):
            count=count+1
        else:
            countp=countp+1
    if(count>countp):
        al[i]=0
    else:
        al[i]=1

In [105]:
y_test.shape

(230,)

In [106]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test, al)
print(cm)
print(accuracy_score(y_test,al))

[[115   0]
 [ 46  69]]
0.8


In [107]:
#feataure scaling
'''from sklearn.preprocessing import StandardScaler
ac=StandardScaler()
x_train=ac.fit_transform(x_train)
x_test=ac.transform(x_test)'''

'from sklearn.preprocessing import StandardScaler\nac=StandardScaler()\nx_train=ac.fit_transform(x_train)\nx_test=ac.transform(x_test)'

In [108]:
for i in range(3,30):
    from sklearn.model_selection import train_test_split
    from sklearn.neighbors import KNeighborsClassifier 
    x_train,x_test,y_train,y_test=train_test_split(aData,xpAll,test_size=0.1,stratify=xpAll,random_state=0)
    classknn=KNeighborsClassifier(n_neighbors=i,metric='minkowski',p=2)
    classknn.fit(x_train,y_train)
    y_pred=classknn.predict(x_test)
    from sklearn.metrics import confusion_matrix, accuracy_score
    cm= confusion_matrix(y_test, y_pred)
    print(cm)
    print(accuracy_score(y_test,y_pred))

[[44 14]
 [22 35]]
0.6869565217391305
[[54  4]
 [24 33]]
0.7565217391304347
[[49  9]
 [21 36]]
0.7391304347826086
[[52  6]
 [25 32]]
0.7304347826086957
[[51  7]
 [24 33]]
0.7304347826086957
[[54  4]
 [25 32]]
0.7478260869565218
[[51  7]
 [23 34]]
0.7391304347826086
[[55  3]
 [27 30]]
0.7391304347826086
[[54  4]
 [25 32]]
0.7478260869565218
[[55  3]
 [26 31]]
0.7478260869565218
[[55  3]
 [26 31]]
0.7478260869565218
[[56  2]
 [27 30]]
0.7478260869565218
[[56  2]
 [25 32]]
0.7652173913043478
[[58  0]
 [26 31]]
0.7739130434782608
[[57  1]
 [25 32]]
0.7739130434782608
[[57  1]
 [26 31]]
0.7652173913043478
[[57  1]
 [25 32]]
0.7739130434782608
[[57  1]
 [26 31]]
0.7652173913043478
[[57  1]
 [26 31]]
0.7652173913043478
[[57  1]
 [26 31]]
0.7652173913043478
[[57  1]
 [26 31]]
0.7652173913043478
[[57  1]
 [26 31]]
0.7652173913043478
[[57  1]
 [26 31]]
0.7652173913043478
[[58  0]
 [26 31]]
0.7739130434782608
[[58  0]
 [25 32]]
0.782608695652174
[[58  0]
 [25 32]]
0.782608695652174
[[58  0]
 [24 

In [109]:
#splitting the data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(aData,xpAll,test_size=0.2,stratify=xpAll,random_state=0)


In [110]:
#train the model using knn classifier
from sklearn.neighbors import KNeighborsClassifier 
classknn=KNeighborsClassifier(n_neighbors=3,metric='minkowski',p=2)
classknn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [111]:
#predicting the test data
y_pred=classknn.predict(x_test)
#y_pred.shape
#y_pred=classifier.predict(y_test_n)
#print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

In [112]:
#checking accuracy score and confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test,y_pred))

[[93 22]
 [39 76]]
0.7347826086956522


In [113]:
from sklearn.metrics import precision_score, recall_score, f1_score, cohen_kappa_score

# Assuming you have true labels (y_true) and predicted labels (y_pred)
# Replace y_true and y_pred with your actual data

# Calculate precision
precision = precision_score(y_test, y_pred, average='weighted')  # You can change the average parameter

# Calculate recall
recall = recall_score(y_test, y_pred, average='weighted')  # You can change the average parameter

# Calculate F1-score
f1 = f1_score(y_test, y_pred, average='weighted')  # You can change the average parameter
kappa = cohen_kappa_score(y_test, y_pred)
# Print the results
print(f"Cohen's Kappa: {kappa}")
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:",f1)

Cohen's Kappa: 0.4695652173913043
Precision: 0.7400278293135436
Recall: 0.7347826086956522
F1-score: 0.733325730360571


In [114]:
from sklearn.model_selection import GridSearchCV, train_test_split
from scipy.stats import pearsonr
from sklearn.metrics import confusion_matrix, accuracy_score
#from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier 
mic_scores = []
selected_features=[]

acc_scores=[]
def calculate_MIC(x, y):
    # Calculate Pearson correlation coefficient (r) between x and y
    r, _ = pearsonr(x, y)
    
    # Calculate MIC using the formula MIC = |r| * log2(n)
    n = len(x)
    mic = abs(r) * np.log2(n)
    
    return mic

for i in range(0,352):
    mic_score = calculate_MIC(aData[:, i], xpAll)
    mic_scores.append(mic_score)


# Sort features based on MIC scores (in descending order)
sorted_features = np.argsort(mic_scores)[::-1]

# Select the top 20 features
for i in range(2,352):
    top_20_features = sorted_features[:i]
    top_20_feature_values = aData[:, top_20_features]
    
    x_train,x_test,y_train,y_test=train_test_split(top_20_feature_values,xpAll,test_size=0.1,stratify=xpAll,random_state=0)
   
    for j in range(3,20):
        classknn=KNeighborsClassifier(n_neighbors=j,metric='minkowski',p=2)
        classknn.fit(x_train,y_train)
        y_pred=classknn.predict(x_test)
        cm= confusion_matrix(y_test, y_pred)
        acc_score=accuracy_score(y_test,y_pred)
        acc_scores.append(acc_score)
        #if(accuracy_score(y_test,y_pred)>0.75):
         #   print("No of Feature selected and neighbour :",i,j)
          #  print(accuracy_score(y_test,y_pred))
          #  print(cm)
        
sorted_acc_scores = np.argsort(mic_scores)[::-1]       

In [115]:
#selecting only the features which has gained highest accuracy in mic feature selection and checking accuracy score with confusion matrix
top_20_features = sorted_features[:3]
top_20_feature_values = aData[:, top_20_features]
#train-test
x_train,x_test,y_train,y_test=train_test_split(top_20_feature_values,xpAll,test_size=0.2,stratify=xpAll,random_state=0)
#feature-scaling
#classification
classknn=KNeighborsClassifier(n_neighbors=6,metric='minkowski',p=2)
classknn.fit(x_train,y_train)
#prediction
y_pred=classknn.predict(x_test)
#confusion matrix
cm= confusion_matrix(y_test, y_pred)
print("No of Feature selected :219 no of neighbours: 7")
print(cm)
print(accuracy_score(y_test,y_pred))

No of Feature selected :219 no of neighbours: 7
[[110   5]
 [ 45  70]]
0.782608695652174


In [116]:
from sklearn.metrics import precision_score, recall_score, f1_score, cohen_kappa_score

# Assuming you have true labels (y_true) and predicted labels (y_pred)
# Replace y_true and y_pred with your actual data

# Calculate precision
precision = precision_score(y_test, y_pred, average='weighted')  # You can change the average parameter

# Calculate recall
recall = recall_score(y_test, y_pred, average='weighted')  # You can change the average parameter

# Calculate F1-score
f1 = f1_score(y_test, y_pred, average='weighted')  # You can change the average parameter
kappa = cohen_kappa_score(y_test, y_pred)
# Print the results
print(f"Cohen's Kappa: {kappa}")
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:",f1)

Cohen's Kappa: 0.5652173913043479
Precision: 0.8215053763440859
Recall: 0.782608695652174
F1-score: 0.7758284600389864
